Repository Atractorrr/Attraction-Server, pull requests merged in 2024-05, with the labels that each got.

#6 [ATR-63] 뉴스레터 get API 구현
  src/main/java/run/attraction/api/v1/introduction/controller/IntroductionController.java
  src/main/java/run/attraction/api/v1/introduction/dto/response/NewsletterResponse.java
  src/main/java/run/attraction/api/v1/introduction/exception/ErrorMessages.java
  src/main/java/run/attraction/api/v1/introduction/exception/GlobalExceptionHandler.java
  src/main/java/run/attraction/api/v1/introduction/exception/IntroductionExceptionHandler.java
  src/main/java/run/attraction/api/v1/introduction/exception/ResourceNotFoundException.java
  src/main/java/run/attraction/api/v1/introduction/repository/NewsletterRepository.java
  src/main/java/run/attraction/api/v1/introduction/service/IntroductionService.java
  src/test/java/run/attraction/api/v1/introduction/controller/IntroductionControllerTest.java
  src/test/java/run/attraction/api/v1/introduction/service/IntroductionServiceTest.java
Labels: feat

#9 [ATR-64] feat: 이전 articles get api
  src/main/java/run/attraction/api/v1/introduction/controller/IntroductionController.java
  src/main/java/run/attraction/api/v1/introduction/dto/response/PreviousArticleResponse.java
  src/main/java/run/attraction/api/v1/introduction/exception/ErrorMessages.java
  src/main/java/run/attraction/api/v1/introduction/exception/IntroductionExceptionHandler.java
  src/main/java/run/attraction/api/v1/introduction/service/IntroductionService.java
  src/test/java/run/attraction/api/v1/introduction/controller/IntroductionControllerTest.java
  src/test/java/run/attraction/api/v1/introduction/service/IntroductionServiceTest.java
Labels: feat

#10 [ATR-66] feat: 관련된 뉴스레터 get api
  src/main/java/run/attraction/api/v1/introduction/controller/IntroductionController.java
  src/main/java/run/attraction/api/v1/introduction/dto/response/NewslettersByCategoryResponse.java
  src/main/java/run/attraction/api/v1/introduction/exception/ErrorMessages.java
  src/main/java/run/attraction/api/v1/introduction/repository/NewsletterRepository.java
  src/main/java/run/attraction/api/v1/introduction/service/IntroductionService.java
  src/test/java/run/attraction/api/v1/introduction/controller/IntroductionControllerTest.java
  src/test/java/run/attraction/api/v1/introduction/service/IntroductionServiceTest.java
Labels: feat

#19 [ATR-106] feat: entity 수정 (#18)
  src/main/java/run/attraction/api/v1/archive/Article.java
  src/main/java/run/attraction/api/v1/introduction/Newsletter.java
Labels: feat

#21 [ATR - 106] feat : 뉴스레터 소개페이지 api 수정
  src/main/java/run/attraction/api/v1/archive/AdminArticle.java
  src/main/java/run/attraction/api/v1/archive/Article.java
  src/main/java/run/attraction/api/v1/archive/repository/AdminArticleRepository.java
  src/main/java/run/attraction/api/v1/archive/repository/ArticleRepository.java
  src/main/java/run/attraction/api/v1/archive/repository/ArticleRepositoryImpl.java
  src/main/java/run/attraction/api/v1/introduction/controller/IntroductionController.java
  src/main/java/run/attraction/api/v1/introduction/dto/response/ApiResponse.java
  src/main/java/run/attraction/api/v1/introduction/dto/response/NewsletterResponse.java
  src/main/java/run/attraction/api/v1/introduction/dto/response/NewslettersByCategoryResponse.java
  src/main/java/run/attraction/api/v1/introduction/dto/response/PreviousArticleResponse.java
  src/main/java/run/attraction/api/v1/introduction/repository/NewsletterRepository.java
  src/main/java/run/attraction/api/v1/introduction/service/IntroductionService.java
  src/main/resources/data.sql
  src/test/java/run/attraction/api/v1/introduction/controller/IntroductionControllerTest.java
  src/test/java/run/attraction/api/v1/introduction/service/IntroductionServiceTest.java
Labels: feat

#22 [ATR - 105] feat : modify code
  src/main/java/run/attraction/api/v1/archive/AdminArticle.java
  src/main/java/run/attraction/api/v1/archive/Article.java
  src/main/java/run/attraction/api/v1/archive/repository/AdminArticleRepository.java
  src/main/java/run/attraction/api/v1/archive/repository/ArticleRepository.java
  src/main/java/run/attraction/api/v1/archive/repository/ArticleRepositoryImpl.java
  src/main/java/run/attraction/api/v1/auth/config/properties/GoogleLoginProperties.java
  src/main/java/run/attraction/api/v1/auth/controller/AuthController.java
  src/main/java/run/attraction/api/v1/auth/provider/google/GoogleOAuthService.java
  src/main/java/run/attraction/api/v1/auth/service/AuthService.java
  src/main/java/run/attraction/api/v1/auth/service/dto/UserTokenDto.java
  src/main/java/run/attraction/api/v1/auth/service/dto/join/JoinRequestDto.java
  src/main/java/run/attraction/api/v1/auth/service/dto/login/FirstLoginResponseDto.java
  src/main/java/run/attraction/api/v1/auth/service/helper/AuthProviderAndTokenHelper.java
  src/main/java/run/attraction/api/v1/auth/service/helper/JoinHelper.java
  src/main/java/run/attraction/api/v1/auth/token/RefreshToken.java
  src/main/java/run/attraction/api/v1/auth/token/jwt/JwtServiceImpl.java
  src/main/java/run/attraction/api/v1/introduction/controller/IntroductionController.java
  src/main/java/run/attraction/api/v1/introduction/dto/response/ApiResponse.java
  src/main/java/run/attraction/api/v1/introduction/dto/response/NewsletterResponse.java
  src/main/java/run/attraction/api/v1/introduction/dto/response/NewslettersByCategoryResponse.java
  src/main/java/run/attraction/api/v1/introduction/dto/response/PreviousArticleResponse.java
  src/main/java/run/attraction/api/v1/introduction/repository/NewsletterRepository.java
  src/main/java/run/attraction/api/v1/introduction/service/IntroductionService.java
  src/main/java/run/attraction/api/v1/mypage/controller/MyPageController.java
  src/main/java/run/attraction/api/v1/mypage/service/MypageService.java
  src/main/java/run/attraction/api/v1/mypage/service/dto/UserDetaiilDto.java
  src/main/java/run/attraction/api/v1/mypage/service/user/MyPageUserSeriveImpl.java
  src/main/java/run/attraction/api/v1/mypage/service/user/MyPageUserService.java
  src/main/java/run/attraction/api/v1/user/User.java
  src/main/java/run/attraction/api/v1/user/init/Userinit.java
  src/main/java/run/attraction/api/v1/user/service/UserServiceImpl.java
  src/main/resources/data.sql
  src/test/java/run/attraction/api/v1/introduction/controller/IntroductionControllerTest.java
  src/test/java/run/attraction/api/v1/introduction/service/IntroductionServiceTest.java
Labels: feat

#23 [ATR - 122] feat: modify code
  src/main/java/run/attraction/api/v1/archive/InBox.java
  src/main/java/run/attraction/api/v1/archive/ReadBox.java
  src/main/java/run/attraction/api/v1/archive/controller/ArchiveController.java
  src/main/java/run/attraction/api/v1/archive/dto/ArticleDTO.java
  src/main/java/run/attraction/api/v1/archive/dto/NewsletterDTO.java
  src/main/java/run/attraction/api/v1/archive/dto/request/UserArticlesRequest.java
  src/main/java/run/attraction/api/v1/archive/repository/ArticleRepositoryCustom.java
  src/main/java/run/attraction/api/v1/archive/repository/ArticleRepositoryImpl.java
  src/main/java/run/attraction/api/v1/archive/service/ArchiveService.java
  src/main/resources/data.sql
Labels: feat

#24 [ATR-6] feat: 마이페이지 유저정보 API 수정 및 ReadBox Repository 생성
  src/main/java/run/attraction/api/v1/archive/repository/ReadBoxRepository.java
  src/main/java/run/attraction/api/v1/mypage/controller/MyPageController.java
  src/main/java/run/attraction/api/v1/mypage/service/MypageService.java
  src/main/java/run/attraction/api/v1/mypage/service/dto/UserDetailDto.java
  src/main/java/run/attraction/api/v1/mypage/service/dto/UserDetailsResponseDto.java
  src/main/java/run/attraction/api/v1/mypage/service/user/MyPageUserSeriveImpl.java
  src/main/java/run/attraction/api/v1/mypage/service/user/MyPageUserService.java
Labels: feat

#26 [ATR - 128] feat: 유저 아티클 퍼센테지 업데이트 기능 구현
  src/main/java/run/attraction/api/v1/archive/controller/ArchiveController.java
  src/main/java/run/attraction/api/v1/archive/repository/ReadBoxRepository.java
  src/main/java/run/attraction/api/v1/archive/service/ArchiveService.java
Labels: feat

#27 [ATR-91] feature: 마이페이지 잔디밭 API
  src/main/java/run/attraction/api/v1/mypage/controller/MyPageController.java
  src/main/java/run/attraction/api/v1/mypage/service/MypageService.java
  src/main/java/run/attraction/api/v1/mypage/service/calendar/MypageCalendarService.java
  src/main/java/run/attraction/api/v1/mypage/service/calendar/MypageCalendarServiceImpl.java
  src/main/java/run/attraction/api/v1/mypage/service/dto/calendar/CalendarDay.java
  src/main/java/run/attraction/api/v1/mypage/service/dto/calendar/CalendarResponseDto.java
  src/main/java/run/attraction/api/v1/mypage/service/dto/userDetail/UserDetailDto.java
  src/main/java/run/attraction/api/v1/mypage/service/dto/userDetail/UserDetailsResponseDto.java
  src/main/java/run/attraction/api/v1/mypage/service/user/MyPageUserService.java
  src/main/java/run/attraction/api/v1/mypage/service/user/MypageUserServiceImpl.java
  src/main/resources/data.sql
Labels: feat

#30 [ATR-158] refactor: user article percentage
  src/main/java/run/attraction/AttractionApplication.java
  src/main/java/run/attraction/api/v1/archive/AdminArticle.java
  src/main/java/run/attraction/api/v1/archive/Article.java
  src/main/java/run/attraction/api/v1/archive/AuditableEntity.java
  src/main/java/run/attraction/api/v1/archive/ReadBox.java
  src/main/java/run/attraction/api/v1/archive/controller/ArchiveController.java
  src/main/java/run/attraction/api/v1/archive/service/ArchiveService.java
  src/main/java/run/attraction/api/v1/introduction/exception/ErrorMessages.java
Labels: refactor

#35 [ATR-165] feat: 프로필 이미지 수정 API
  src/main/java/run/attraction/api/v1/mypage/controller/MypageController.java
  src/main/java/run/attraction/api/v1/mypage/service/MypageService.java
  src/main/java/run/attraction/api/v1/mypage/service/dto/userDetail/UpdateProfileImgRequestDto.java
  src/main/java/run/attraction/api/v1/mypage/service/user/MypageUserService.java
  src/main/java/run/attraction/api/v1/mypage/service/user/MypageUserServiceImpl.java
  src/main/java/run/attraction/api/v1/user/User.java
  src/test/java/run/attraction/api/v1/mypage/service/user/MypageUserServiceTest.java
Labels: feat

#36 [ATR-166] feat: 마이페이지 배경 이미지 수정 API
  src/main/java/run/attraction/api/v1/mypage/controller/MypageController.java
  src/main/java/run/attraction/api/v1/mypage/service/MypageService.java
  src/main/java/run/attraction/api/v1/mypage/service/dto/userDetail/UpdateBackgroundImgRequestDto.java
  src/main/java/run/attraction/api/v1/mypage/service/user/MypageUserService.java
  src/main/java/run/attraction/api/v1/mypage/service/user/MypageUserServiceImpl.java
  src/test/java/run/attraction/api/v1/mypage/service/user/MypageUserServiceTest.java
Labels: feat

#37 [ATR - 164] feat: percentage 업데이트 시 readBox가 존재하지 않으면 생성
  src/main/java/run/attraction/api/v1/archive/ReadBox.java
  src/main/java/run/attraction/api/v1/archive/controller/ArchiveController.java
  src/main/java/run/attraction/api/v1/archive/service/ArchiveService.java
Labels: feat

#38 [ATR-167] feat: 유저가 뉴스레터 구독하면 구독함에 추가
  src/main/java/run/attraction/api/v1/archive/Subscribe.java
  src/main/java/run/attraction/api/v1/archive/controller/ArchiveController.java
  src/main/java/run/attraction/api/v1/archive/repository/SubscribeRepository.java
  src/main/java/run/attraction/api/v1/archive/service/ArchiveService.java
Labels: feat

#40 [ATR-170] feat : google refresh token 추가
  build.gradle
  src/main/java/run/attraction/api/v1/auth/config/AuthProviderConfig.java
  src/main/java/run/attraction/api/v1/auth/controller/AuthTestController.java
  src/main/java/run/attraction/api/v1/auth/provider/AuthProvider.java
  src/main/java/run/attraction/api/v1/auth/provider/oauth/OAuthToken.java
  src/main/java/run/attraction/api/v1/auth/token/GoogleRefreshToken.java
  src/main/java/run/attraction/api/v1/auth/token/repository/GoogleRefreshTokenRepository.java
  src/main/java/run/attraction/api/v1/user/User.java
  src/main/resources/data.sql
Labels: feat

#41 [ATR-170] feat: google refresh token 추가
  build.gradle
  src/main/java/run/attraction/api/v1/auth/config/AuthProviderConfig.java
  src/main/java/run/attraction/api/v1/auth/controller/AuthController.java
  src/main/java/run/attraction/api/v1/auth/controller/AuthTestController.java
  src/main/java/run/attraction/api/v1/auth/provider/AuthProvider.java
  src/main/java/run/attraction/api/v1/auth/provider/google/GoogleOAuthService.java
  src/main/java/run/attraction/api/v1/auth/provider/oauth/OAuthToken.java
  src/main/java/run/attraction/api/v1/auth/service/dto/login/LoginResponseDto.java
  src/main/java/run/attraction/api/v1/auth/token/GoogleRefreshToken.java
  src/main/java/run/attraction/api/v1/auth/token/repository/GoogleRefreshTokenRepository.java
  src/main/java/run/attraction/api/v1/user/Occupation.java
  src/main/java/run/attraction/api/v1/user/User.java
  src/main/resources/data.sql
Labels: feat

#42 [ATR-6] feat: 마이페이지 API 추가
  src/main/java/run/attraction/api/v1/mypage/controller/MypageController.java
  src/main/java/run/attraction/api/v1/mypage/service/MypageService.java
  src/main/java/run/attraction/api/v1/mypage/service/archive/article/MypageArticleServiceImpl.java
  src/main/java/run/attraction/api/v1/mypage/service/dto/userDetail/UpdateBackgroundImgRequestDto.java
  src/main/java/run/attraction/api/v1/mypage/service/dto/userDetail/UpdateProfileImgRequestDto.java
  src/main/java/run/attraction/api/v1/mypage/service/user/MypageUserService.java
  src/main/java/run/attraction/api/v1/mypage/service/user/MypageUserServiceImpl.java
  src/main/java/run/attraction/api/v1/user/User.java
  src/main/resources/data.sql
  src/test/java/run/attraction/api/v1/mypage/service/user/MypageUserServiceTest.java
Labels: feat

#44 [ATR-134] feat: 마이페이지 개인 설정
  src/main/java/run/attraction/api/v1/mypage/controller/MypageController.java
  src/main/java/run/attraction/api/v1/mypage/service/MypageService.java
  src/main/java/run/attraction/api/v1/mypage/service/dto/userDetail/UpdateUserDetailDto.java
  src/main/java/run/attraction/api/v1/mypage/service/dto/userDetail/UpdateUserDetailRequestDto.java
  src/main/java/run/attraction/api/v1/mypage/service/user/MypageUserService.java
  src/main/java/run/attraction/api/v1/mypage/service/user/MypageUserServiceImpl.java
  src/main/java/run/attraction/api/v1/user/User.java
  src/test/java/run/attraction/api/v1/mypage/service/user/MypageUserServiceTest.java
Labels: feat

#46 [ATR-6] feat: 마이페이지 API 추가 및 수정
  src/main/java/run/attraction/api/v1/mypage/controller/MypageController.java
  src/main/java/run/attraction/api/v1/mypage/service/MypageService.java
  src/main/java/run/attraction/api/v1/mypage/service/archive/newsletter/MypageNewsletterService.java
  src/main/java/run/attraction/api/v1/mypage/service/archive/newsletter/MypageNewsletterServiceImpl.java
  src/main/java/run/attraction/api/v1/mypage/service/dto/archive/newsletter/MypageNewsletterDetail.java
  src/main/java/run/attraction/api/v1/mypage/service/dto/archive/newsletter/SubscribeResponseDto.java
  src/main/java/run/attraction/api/v1/mypage/service/dto/userDetail/UpdateUserDetailDto.java
  src/main/java/run/attraction/api/v1/mypage/service/dto/userDetail/UpdateUserDetailRequestDto.java
  src/main/java/run/attraction/api/v1/mypage/service/dto/userDetail/UserDetailDto.java
  src/main/java/run/attraction/api/v1/mypage/service/user/MypageUserService.java
  src/main/java/run/attraction/api/v1/mypage/service/user/MypageUserServiceImpl.java
  src/main/java/run/attraction/api/v1/user/User.java
  src/main/resources/data.sql
  src/test/java/run/attraction/api/v1/mypage/service/archive/MypageNewsletterSerivceTest.java
  src/test/java/run/attraction/api/v1/mypage/service/user/MypageUserServiceTest.java
Labels: feat

#47 [ATR-177] feat: 로그인 반환값 변경
  src/main/java/run/attraction/api/v1/auth/controller/AuthController.java
  src/main/java/run/attraction/api/v1/auth/provider/AuthProvider.java
  src/main/java/run/attraction/api/v1/auth/service/dto/UserTokenDto.java
  src/main/java/run/attraction/api/v1/auth/service/dto/login/LoginResponseDto.java
  src/main/java/run/attraction/api/v1/auth/service/helper/AuthProviderAndTokenHelper.java
  src/main/java/run/attraction/api/v1/auth/token/GoogleRefreshToken.java
  src/main/java/run/attraction/api/v1/auth/token/repository/GoogleRefreshTokenRepository.java
Labels: feat

#48 [ATR-162] feat: 트렌디한 뉴스레터 카테고리 API
  src/main/java/run/attraction/api/v1/home/controller/HomeController.java
  src/main/java/run/attraction/api/v1/home/service/HomeService.java
  src/main/java/run/attraction/api/v1/home/service/dto/categories/CategoriesResponseDto.java
  src/main/java/run/attraction/api/v1/home/service/newsletter/HomeNewsletterService.java
  src/main/java/run/attraction/api/v1/home/service/newsletter/HomeNewsletterServiceImpl.java
  src/test/java/run/attraction/api/v1/home/service/HomeServiceTest.java
Labels: feat

#50 [ATR-160] feat: 메인페이지 최근 받은 뉴스레터 API
  src/main/java/run/attraction/api/v1/archive/repository/ArticleRepository.java
  src/main/java/run/attraction/api/v1/home/controller/HomeController.java
  src/main/java/run/attraction/api/v1/home/service/HomeService.java
  src/main/java/run/attraction/api/v1/home/service/article/HomeArticleService.java
  src/main/java/run/attraction/api/v1/home/service/article/HomeArticleServiceImpl.java
  src/main/java/run/attraction/api/v1/home/service/dto/article/ArticleDetailDto.java
  src/main/java/run/attraction/api/v1/home/service/dto/article/ReceivedArticlesResponseDto.java
  src/main/resources/data.sql
Labels: feat

#51 [ATR-24] feat: 메인페이지 API
  src/main/java/run/attraction/api/v1/archive/repository/ArticleRepository.java
  src/main/java/run/attraction/api/v1/archive/repository/SubscribeRepository.java
  src/main/java/run/attraction/api/v1/home/controller/HomeController.java
  src/main/java/run/attraction/api/v1/home/service/HomeService.java
  src/main/java/run/attraction/api/v1/home/service/article/HomeArticleService.java
  src/main/java/run/attraction/api/v1/home/service/article/HomeArticleServiceImpl.java
  src/main/java/run/attraction/api/v1/home/service/dto/article/ArticleDetailDto.java
  src/main/java/run/attraction/api/v1/home/service/dto/article/ReceivedArticlesResponseDto.java
  src/main/java/run/attraction/api/v1/home/service/dto/categories/CategoriesResponseDto.java
  src/main/java/run/attraction/api/v1/home/service/dto/newsletter/NewsletterDetailDto.java
  src/main/java/run/attraction/api/v1/home/service/dto/newsletter/NewslettersResponseDto.java
  src/main/java/run/attraction/api/v1/home/service/newsletter/HomeNewsletterService.java
  src/main/java/run/attraction/api/v1/home/service/newsletter/HomeNewsletterServiceImpl.java
  src/main/java/run/attraction/api/v1/introduction/Newsletter.java
  src/main/java/run/attraction/api/v1/introduction/repository/NewsletterRepository.java
  src/main/resources/data.sql
  src/test/java/run/attraction/api/v1/home/service/HomeServiceTest.java
Labels: feat

#52 Chore/atr 173 setting deploy
  .github/workflows/deploy.yml
  .gitignore
  Dockerfile
  build.gradle
Labels: chore

#57 [ATR-92] feat: 최근 읽은 아티클 API 반환값 수정
  src/main/java/run/attraction/api/v1/archive/repository/ArticleRepository.java
  src/main/java/run/attraction/api/v1/mypage/service/archive/article/MypageArticleServiceImpl.java
  src/main/java/run/attraction/api/v1/mypage/service/dto/archive/article/UserArticleDetail.java
  src/main/resources/data.sql
Labels: feat

#63 배포 테스트 5
  src/main/java/run/attraction/api/v1/auth/controller/AuthController.java
  src/main/java/run/attraction/api/v1/auth/provider/AuthProvider.java
  src/main/java/run/attraction/api/v1/auth/service/AuthService.java
  src/main/java/run/attraction/api/v1/auth/service/helper/AuthProviderAndTokenHelper.java
Labels: feat

#66 배포 테스트 8
  src/main/java/run/attraction/api/v1/auth/controller/AuthController.java
  src/main/java/run/attraction/api/v1/auth/provider/AuthProvider.java
  src/main/java/run/attraction/api/v1/auth/provider/google/GoogleOAuthService.java
  src/main/java/run/attraction/api/v1/auth/service/AuthService.java
  src/main/java/run/attraction/api/v1/auth/service/helper/AuthProviderAndTokenHelper.java
  src/main/java/run/attraction/api/v1/user/service/UserServiceImpl.java
Labels: chore

#75 [ATR-204] remove: Uploadays enum 삭제
  src/main/java/run/attraction/api/v1/introduction/Newsletter.java
  src/main/java/run/attraction/api/v1/introduction/UploadDays.java
  src/main/java/run/attraction/api/v1/introduction/dto/response/NewsletterResponse.java
  src/main/resources/data.sql
  src/test/java/run/attraction/api/v1/introduction/UploadDaysTest.java
Labels: remove

#76 [ATR-207] : feat: subscribe 엔티티 수정
  src/main/java/run/attraction/api/v1/archive/Subscribe.java
  src/main/java/run/attraction/api/v1/archive/controller/ArchiveController.java
  src/main/java/run/attraction/api/v1/archive/repository/SubscribeRepository.java
  src/main/java/run/attraction/api/v1/archive/service/ArchiveService.java
  src/main/java/run/attraction/api/v1/introduction/repository/NewsletterRepository.java
  src/main/java/run/attraction/api/v1/mypage/service/archive/newsletter/MypageNewsletterServiceImpl.java
  src/main/resources/data.sql
Labels: feat

#77 [ATR-208] feat: 로그인 & 회원가입 로직 수정
  src/main/java/run/attraction/api/v1/auth/controller/AuthController.java
  src/main/java/run/attraction/api/v1/auth/service/dto/UserTokenDto.java
  src/main/java/run/attraction/api/v1/auth/service/dto/login/FirstLoginResponseDto.java
  src/main/java/run/attraction/api/v1/auth/service/dto/login/LoginResponseDto.java
  src/main/java/run/attraction/api/v1/auth/service/helper/AuthProviderAndTokenHelper.java
  src/main/java/run/attraction/api/v1/auth/service/helper/JoinHelper.java
  src/main/java/run/attraction/api/v1/auth/token/CookieTokenSetter.java
  src/main/java/run/attraction/api/v1/home/service/HomeService.java
  src/main/java/run/attraction/api/v1/home/service/newsletter/HomeNewsletterService.java
  src/main/java/run/attraction/api/v1/home/service/newsletter/HomeNewsletterServiceImpl.java
  src/main/java/run/attraction/api/v1/mypage/service/user/MypageUserServiceImpl.java
  src/main/java/run/attraction/api/v1/user/User.java
  src/main/java/run/attraction/api/v1/user/UserDetail.java
  src/main/java/run/attraction/api/v1/user/repository/UserDetailRepository.java
  src/main/java/run/attraction/api/v1/user/repository/UserRepository.java
  src/main/java/run/attraction/api/v1/user/service/UserServiceImpl.java
  src/main/resources/data.sql
Labels: feat
