Repository Atractorrr/Attraction-Server, pull requests merged in 2024-07, with the labels that each got.

#234 [ATR-514] chore: API 명세를 위한 스웨거 도입
  build.gradle
  src/main/java/run/attraction/api/swagger/SwaggerConfig.java
  src/main/java/run/attraction/api/v1/archive/controller/ArchiveController.java
  src/main/java/run/attraction/api/v1/auth/config/ApplicationConfig.java
  src/main/java/run/attraction/api/v1/auth/controller/AuthController.java
  src/main/java/run/attraction/api/v1/bookmark/controller/BookmarkController.java
  src/main/java/run/attraction/api/v1/home/controller/HomeController.java
  src/main/java/run/attraction/api/v1/introduction/controller/IntroductionController.java
  src/main/java/run/attraction/api/v1/introduction/controller/SubscriptionController.java
  src/main/java/run/attraction/api/v1/mypage/controller/MypageController.java
  src/main/java/run/attraction/api/v1/rank/controller/RankController.java
  src/main/java/run/attraction/api/v1/statistics/controller/StatisticsController.java
Labels: feat

#235 chore: 스웨거 시큐티리 적용
  src/main/java/run/attraction/api/v1/auth/config/SecurityConfig.java
  src/main/java/run/attraction/api/v1/auth/filter/SessionFilter.java
  src/main/java/run/attraction/api/v1/user/Role.java
Labels: chore

#236 [ATR-514] chore: 스웨거 적용
  build.gradle
  src/main/java/run/attraction/api/swagger/SwaggerConfig.java
  src/main/java/run/attraction/api/v1/archive/controller/ArchiveController.java
  src/main/java/run/attraction/api/v1/auth/config/ApplicationConfig.java
  src/main/java/run/attraction/api/v1/auth/config/SecurityConfig.java
  src/main/java/run/attraction/api/v1/auth/controller/AuthController.java
  src/main/java/run/attraction/api/v1/auth/filter/SessionFilter.java
  src/main/java/run/attraction/api/v1/bookmark/controller/BookmarkController.java
  src/main/java/run/attraction/api/v1/home/controller/HomeController.java
  src/main/java/run/attraction/api/v1/introduction/controller/IntroductionController.java
  src/main/java/run/attraction/api/v1/introduction/controller/SubscriptionController.java
  src/main/java/run/attraction/api/v1/mypage/controller/MypageController.java
  src/main/java/run/attraction/api/v1/rank/controller/RankController.java
  src/main/java/run/attraction/api/v1/statistics/controller/StatisticsController.java
  src/main/java/run/attraction/api/v1/user/Role.java
Labels: feat

#237 hotfix: 스웨거 운영서버 링크 변경
  src/main/java/run/attraction/api/swagger/SwaggerConfig.java
Labels: bug

#238 hotfix: 스웨거 운영서버 링크 변경 (#237)
  src/main/java/run/attraction/api/swagger/SwaggerConfig.java
Labels: hotfix

#239 chore: 스웨거 Security 수정
  src/main/java/run/attraction/api/v1/auth/config/SecurityConfig.java
Labels: chore

#243 [ATR-522] feat: 세션으로 유저 정보 조회 API 수정
  src/main/java/run/attraction/api/v1/auth/session/dto/UserDetailBySession.java
  src/main/java/run/attraction/api/v1/user/repository/UserRepository.java
Labels: feat

#244 [ATR-522] feat: 세션으로 유저 정보 조회 API 수정 (#243)
  src/main/java/run/attraction/api/v1/auth/session/dto/UserDetailBySession.java
  src/main/java/run/attraction/api/v1/user/repository/UserRepository.java
Labels: feat

#245 [ATR-525] test: 뉴스레터 변수 추가로 테스트 수정
  src/test/java/run/attraction/api/v1/introduction/repository/NewsletterRepositoryTest.java
  src/test/resources/sql/data-h2.sql
Labels: test

#246 [ATR-526] chore: 테스트 커버리지 체크를 위한 jacoco 도입
  build.gradle
Labels: chore

#247 [ATR-524] refactor: subscribe 엔티티 리팩터링
  build.gradle
  src/main/java/run/attraction/api/v1/archive/controller/ArchiveController.java
  src/main/java/run/attraction/api/v1/archive/repository/ArticleRepositoryImpl.java
  src/main/java/run/attraction/api/v1/archive/service/ArchiveService.java
  src/main/java/run/attraction/api/v1/home/service/article/HomeArticleServiceImpl.java
  src/main/java/run/attraction/api/v1/home/service/newsletter/HomeNewsletterServiceImpl.java
  src/main/java/run/attraction/api/v1/introduction/Subscription.java
  src/main/java/run/attraction/api/v1/introduction/controller/SubscriptionController.java
  src/main/java/run/attraction/api/v1/introduction/repository/NewsletterRepository.java
  src/main/java/run/attraction/api/v1/introduction/repository/SubscriptionRepository.java
  src/main/java/run/attraction/api/v1/introduction/service/SubscriptionService.java
  src/main/java/run/attraction/api/v1/introduction/utils/SubscriptionUtil.java
  src/main/java/run/attraction/api/v1/mypage/service/archive/newsletter/MypageNewsletterServiceImpl.java
  src/main/resources/data.sql
  src/test/java/run/attraction/api/v1/mypage/service/archive/MypageNewsletterSerivceTest.java
  src/test/resources/sql/bookmark/bookmark-service-test-data.sql
  src/test/resources/sql/data-h2.sql
Labels: refactor

#248 [ATR-524] refactor: subscribe 엔티티 리팩터링 외 2개
  build.gradle
  src/main/java/run/attraction/api/v1/archive/controller/ArchiveController.java
  src/main/java/run/attraction/api/v1/archive/repository/ArticleRepositoryImpl.java
  src/main/java/run/attraction/api/v1/archive/service/ArchiveService.java
  src/main/java/run/attraction/api/v1/home/service/article/HomeArticleServiceImpl.java
  src/main/java/run/attraction/api/v1/home/service/newsletter/HomeNewsletterServiceImpl.java
  src/main/java/run/attraction/api/v1/introduction/Subscription.java
  src/main/java/run/attraction/api/v1/introduction/controller/SubscriptionController.java
  src/main/java/run/attraction/api/v1/introduction/repository/NewsletterRepository.java
  src/main/java/run/attraction/api/v1/introduction/repository/SubscriptionRepository.java
  src/main/java/run/attraction/api/v1/introduction/service/SubscriptionService.java
  src/main/java/run/attraction/api/v1/introduction/utils/SubscriptionUtil.java
  src/main/java/run/attraction/api/v1/mypage/service/archive/newsletter/MypageNewsletterServiceImpl.java
  src/main/resources/data.sql
  src/test/java/run/attraction/api/v1/introduction/repository/NewsletterRepositoryTest.java
  src/test/java/run/attraction/api/v1/mypage/service/archive/MypageNewsletterSerivceTest.java
  src/test/resources/sql/bookmark/bookmark-service-test-data.sql
  src/test/resources/sql/data-h2.sql
Labels: chore, refactor, test

#249 [ATR-534] hotfix: 최근 받은 아티클 로직 쿼리 추가
  src/main/java/run/attraction/api/v1/archive/repository/ArticleRepositoryImpl.java
Labels: hotfix

#250 [ATR-574] fix: 최근 받은 아티클 로직 쿼리 추가 (#249)
  src/main/java/run/attraction/api/v1/archive/repository/ArticleRepositoryImpl.java
Labels: hotfix

#251 [ATR-536] feat: 마이페이지 뉴스레터 구독함 로직 수정
  src/main/java/run/attraction/api/v1/mypage/service/archive/newsletter/MypageNewsletterServiceImpl.java
Labels: feat

#252 [ATR-536] feat: 마이페이지 뉴스레터 구독함 로직 수정 (#251)
  src/main/java/run/attraction/api/v1/mypage/service/archive/newsletter/MypageNewsletterServiceImpl.java
Labels: feat

#253 [ATR-541] fix: 지난 아티클중 일부가 정상적으로 정렬되지 않는 현상을 수정
  src/main/java/run/attraction/api/v1/archive/repository/ArticleRepository.java
  src/main/java/run/attraction/api/v1/introduction/service/IntroductionService.java
Labels: bug

#254 [ATR-541] fix: 지난 아티클중 일부가 정상적으로 정렬되지 않는 현상을 수정 (#253)
  src/main/java/run/attraction/api/v1/archive/repository/ArticleRepository.java
  src/main/java/run/attraction/api/v1/introduction/service/IntroductionService.java
Labels: bug, refactor

#255 [ATR-541] fix: 지난 아티클중 일부가 정상적으로 정렬되지 않는 현상을 수정
  src/main/java/run/attraction/api/v1/archive/repository/ArticleRepository.java
  src/main/java/run/attraction/api/v1/archive/repository/ArticleRepositoryCustom.java
  src/main/java/run/attraction/api/v1/archive/repository/ArticleRepositoryImpl.java
  src/main/java/run/attraction/api/v1/archive/service/ArchiveService.java
  src/main/java/run/attraction/api/v1/introduction/dto/response/PreviousArticleResponse.java
  src/main/java/run/attraction/api/v1/introduction/service/IntroductionService.java
Labels: bug

#256 [ATR-541] fix: 지난 아티클중 일부가 정상적으로 정렬되지 않는 현상을 수정 (#255)
  src/main/java/run/attraction/api/v1/archive/repository/ArticleRepository.java
  src/main/java/run/attraction/api/v1/archive/repository/ArticleRepositoryCustom.java
  src/main/java/run/attraction/api/v1/archive/repository/ArticleRepositoryImpl.java
  src/main/java/run/attraction/api/v1/archive/service/ArchiveService.java
  src/main/java/run/attraction/api/v1/introduction/dto/response/PreviousArticleResponse.java
  src/main/java/run/attraction/api/v1/introduction/service/IntroductionService.java
Labels: bug

#257 fix: 수정하면서 놓친 prefix 추가
  src/main/java/run/attraction/api/v1/introduction/dto/response/PreviousArticleResponse.java
Labels: hotfix

#258 fix: 수정하면서 놓친 prefix 추가 (#257)
  src/main/java/run/attraction/api/v1/introduction/dto/response/PreviousArticleResponse.java
Labels: hotfix

#259 fix: 잘못된 적용된 prefix 수정
  src/main/java/run/attraction/api/v1/introduction/dto/response/PreviousArticleResponse.java
Labels: hotfix

#260 fix: 잘못된 적용된 prefix 수정 (#259)
  src/main/java/run/attraction/api/v1/introduction/dto/response/PreviousArticleResponse.java
Labels: bug, hotfix

#261 [ATR-542] feat: streak 랭킹 시스템 수정
  src/main/java/run/attraction/api/v1/archive/service/ArchiveService.java
  src/main/java/run/attraction/api/v1/rank/ReadBoxEvent.java
  src/main/java/run/attraction/api/v1/rank/service/calculator/ConsistencyRankCalculator.java
Labels: feat

#262 [ATR-542] feat: streak 랭킹 시스템 수정
  src/main/java/run/attraction/api/v1/archive/service/ArchiveService.java
  src/main/java/run/attraction/api/v1/rank/ReadBoxEvent.java
  src/main/java/run/attraction/api/v1/rank/service/calculator/ConsistencyRankCalculator.java
Labels: feat

#263 [ATR-542] feat: streak 랭킹 시스템 수정
  src/main/java/run/attraction/api/v1/archive/service/ArchiveService.java
  src/main/java/run/attraction/api/v1/rank/ReadBoxEvent.java
  src/main/java/run/attraction/api/v1/rank/service/calculator/ConsistencyRankCalculator.java
Labels: feat

#264 [ATR-548] fix: 도커 타임존 서울로 설정
  .github/workflows/deploy.yml
  Dockerfile
Labels: bug

#265 [ATR-548] chore: docker 타임존 서울로 설정 (#264)
  .github/workflows/deploy.yml
  Dockerfile
Labels: bug

#267 [ATR-548] : fix: 아티클 보여주는 일수 수정 (#266)
  src/main/java/run/attraction/api/v1/archive/repository/ArticleRepositoryImpl.java
Labels: bug

#268 [ATR-556] fix: Fix/atr 556 modify localdate
  src/main/java/run/attraction/api/v1/archive/repository/ArticleRepositoryImpl.java
Labels: bug

#269 [ATR-556] fix: 아티클 보관함에서 7일보다 더 이전 아티클이 보이는 현상 수정 (#268)
  src/main/java/run/attraction/api/v1/archive/repository/ArticleRepositoryImpl.java
Labels: bug

#270 [ATR-528] feat: 구독 취소 기능 구현
  src/main/java/run/attraction/api/v1/introduction/Subscription.java
  src/main/java/run/attraction/api/v1/introduction/UserSubscribedNewsletterCategory.java
  src/main/java/run/attraction/api/v1/introduction/controller/SubscriptionController.java
  src/main/java/run/attraction/api/v1/introduction/repository/NewsletterRepository.java
  src/main/java/run/attraction/api/v1/introduction/repository/SubscriptionRepository.java
  src/main/java/run/attraction/api/v1/introduction/repository/UserSubscribedNewsletterCategoryRepository.java
  src/main/java/run/attraction/api/v1/introduction/service/SubscriptionService.java
  src/main/java/run/attraction/api/v1/introduction/utils/SubscriptionUtil.java
  src/main/java/run/attraction/api/v1/mypage/service/archive/newsletter/MypageNewsletterServiceImpl.java
  src/test/java/run/attraction/api/v1/introduction/repository/UserSubscribedNewsletterCategoryRepositoryTest.java
  src/test/java/run/attraction/api/v1/mypage/service/archive/MypageNewsletterSerivceTest.java
Labels: feat

#272 fix: 마이페이지 구독한 뉴스레터가 비정상적으로 많이 출력되는 현상 수정
  src/main/java/run/attraction/api/v1/introduction/repository/SubscriptionRepository.java
  src/main/java/run/attraction/api/v1/mypage/controller/MypageController.java
Labels: bug, hotfix

#273 fix: 마이페이지 구독한 뉴스레터가 비정상적으로 많이 출력되는 현상 수정
  src/main/java/run/attraction/api/v1/introduction/repository/SubscriptionRepository.java
  src/main/java/run/attraction/api/v1/mypage/controller/MypageController.java
Labels: bug, hotfix

#278 [ATR-583] feat: 아티클 필터 추가 - 뉴스레터
  .github/workflows/pull_request.yml
  README.md
  src/main/java/run/attraction/api/v1/archive/dto/request/UserArticlesRequest.java
  src/main/java/run/attraction/api/v1/archive/repository/ArticleRepositoryCustom.java
  src/main/java/run/attraction/api/v1/archive/repository/ArticleRepositoryImpl.java
  src/main/java/run/attraction/api/v1/archive/service/ArchiveService.java
  src/main/java/run/attraction/api/v1/introduction/controller/SubscriptionController.java
  src/main/java/run/attraction/api/v1/introduction/dto/response/SubscribedNewsletterResponse.java
  src/main/java/run/attraction/api/v1/introduction/service/SubscriptionService.java
Labels: feat

#279 [ATR-578] feat: 북마크페이지에서 필터 추가 - 뉴스레터
  src/main/java/run/attraction/api/v1/archive/repository/ArticleRepositoryCustom.java
  src/main/java/run/attraction/api/v1/archive/repository/ArticleRepositoryImpl.java
  src/main/java/run/attraction/api/v1/bookmark/dto/BookmarkArticleRequest.java
  src/main/java/run/attraction/api/v1/bookmark/service/BookmarkService.java
Labels: feat
