Repository Atractorrr/Attraction-Server, pull requests merged in 2024-08, with the labels that each got.

#281 [ATR-598] chore: 패키지 버전 업데이트 및 삭제
  build.gradle
  src/main/java/run/attraction/api/v1/gmail/dto/UserGmailDto.java
  src/main/java/run/attraction/api/v1/gmail/event/SubscribeVo.java
  src/main/java/run/attraction/api/v1/gmail/event/UserSubscribedEvent.java
  src/main/java/run/attraction/api/v1/introduction/event/AutoSubscribeVo.java
  src/test/java/run/attraction/api/v1/introduction/repository/NewsletterRepositoryTest.java
Labels: chore

#282 [ATR-598] chore: 패키지 버전 업데이트 및 삭제 (#281)
  build.gradle
  src/main/java/run/attraction/api/v1/gmail/dto/UserGmailDto.java
  src/main/java/run/attraction/api/v1/gmail/event/SubscribeVo.java
  src/main/java/run/attraction/api/v1/gmail/event/UserSubscribedEvent.java
  src/main/java/run/attraction/api/v1/introduction/event/AutoSubscribeVo.java
  src/test/java/run/attraction/api/v1/introduction/repository/NewsletterRepositoryTest.java
Labels: chore

#283 [ATR-599] fix: 구독한 뉴스레터를 가져올 때 구독취소한 것도 가져오는 현상 수정
  src/main/java/run/attraction/api/v1/introduction/service/SubscriptionService.java
Labels: bug

#284 Dev
  src/main/java/run/attraction/api/v1/introduction/service/SubscriptionService.java
Labels: bug

#285 [ATR-601] fix: 페이지네이션이 정상적으로 동장하지 않는 현상 수정
  src/main/java/run/attraction/api/v1/archive/repository/ArticleRepositoryImpl.java
Labels: bug

#286 [ATR-601] fix: 페이지네이션이 정상적으로 동장하지 않는 현상 수정 (#285)
  src/main/java/run/attraction/api/v1/archive/repository/ArticleRepositoryImpl.java
Labels: bug

#287 [ATR-595] feat: 세션 Redis 적용
  build.gradle
  src/main/java/run/attraction/api/v1/auth/config/RedisConfig.java
  src/main/java/run/attraction/api/v1/auth/filter/SessionFilter.java
Labels: feat

#288 [ATR-595] feat: 세션 Redis 적용 (#287)
  build.gradle
  src/main/java/run/attraction/api/v1/auth/config/RedisConfig.java
  src/main/java/run/attraction/api/v1/auth/filter/SessionFilter.java
Labels: feat

#289 feat: 세션 적용 Rollback
  build.gradle
  src/main/java/run/attraction/api/v1/auth/config/RedisConfig.java
  src/test/java/run/attraction/api/v1/bookmark/repository/BookmarkRepositoryTest.java
  src/test/java/run/attraction/api/v1/bookmark/service/BookmarkServiceTest.java
Labels: chore
