Repository Atractorrr/Attraction-Server, pull requests merged in 2024-06, with the labels that each got.

#78 feat: dev 변경사항
  src/main/java/run/attraction/api/v1/archive/Subscribe.java
  src/main/java/run/attraction/api/v1/archive/controller/ArchiveController.java
  src/main/java/run/attraction/api/v1/archive/repository/SubscribeRepository.java
  src/main/java/run/attraction/api/v1/archive/service/ArchiveService.java
  src/main/java/run/attraction/api/v1/auth/controller/AuthController.java
  src/main/java/run/attraction/api/v1/auth/service/dto/UserTokenDto.java
  src/main/java/run/attraction/api/v1/auth/service/dto/login/FirstLoginResponseDto.java
  src/main/java/run/attraction/api/v1/auth/service/dto/login/LoginResponseDto.java
  src/main/java/run/attraction/api/v1/auth/service/helper/AuthProviderAndTokenHelper.java
  src/main/java/run/attraction/api/v1/auth/service/helper/JoinHelper.java
  src/main/java/run/attraction/api/v1/auth/token/CookieTokenSetter.java
  src/main/java/run/attraction/api/v1/home/controller/HomeController.java
  src/main/java/run/attraction/api/v1/home/service/HomeService.java
  src/main/java/run/attraction/api/v1/home/service/newsletter/HomeNewsletterService.java
  src/main/java/run/attraction/api/v1/home/service/newsletter/HomeNewsletterServiceImpl.java
  src/main/java/run/attraction/api/v1/introduction/Newsletter.java
  src/main/java/run/attraction/api/v1/introduction/UploadDays.java
  src/main/java/run/attraction/api/v1/introduction/dto/response/NewsletterResponse.java
  src/main/java/run/attraction/api/v1/introduction/repository/NewsletterRepository.java
  src/main/java/run/attraction/api/v1/mypage/controller/MypageController.java
  src/main/java/run/attraction/api/v1/mypage/service/archive/article/MypageArticleServiceImpl.java
  src/main/java/run/attraction/api/v1/mypage/service/archive/newsletter/MypageNewsletterServiceImpl.java
  src/main/java/run/attraction/api/v1/mypage/service/dto/userDetail/UserDetailDto.java
  src/main/java/run/attraction/api/v1/mypage/service/user/MypageUserServiceImpl.java
  src/main/java/run/attraction/api/v1/user/User.java
  src/main/java/run/attraction/api/v1/user/UserDetail.java
  src/main/java/run/attraction/api/v1/user/repository/UserDetailRepository.java
  src/main/java/run/attraction/api/v1/user/repository/UserRepository.java
  src/main/java/run/attraction/api/v1/user/service/UserServiceImpl.java
  src/main/resources/data.sql
  src/test/java/run/attraction/api/v1/introduction/UploadDaysTest.java
Labels: feat

#79 [ATR - 220] feat: response 수정
  src/main/java/run/attraction/api/v1/introduction/dto/response/PreviousArticleResponse.java
  src/main/java/run/attraction/api/v1/introduction/service/IntroductionService.java
Labels: feat

#82 style: 글자 수정 및 UserInit 주석처리
  src/main/java/run/attraction/api/v1/home/service/newsletter/HomeNewsletterServiceImpl.java
Labels: chore

#83 [ATR-221] feat: findAllByIds -> findNewslettersByNewsletterIds로 변경
  src/main/java/run/attraction/api/v1/home/service/newsletter/HomeNewsletterServiceImpl.java
Labels: feat

#84 [ATR-222] style: AuditableEntity 변수명 변경
  src/main/java/run/attraction/api/v1/archive/AuditableEntity.java
  src/main/java/run/attraction/api/v1/mypage/service/archive/article/MypageArticleServiceImpl.java
Labels: style

#85 feat: AuditableEntity 수정 및 적용
  src/main/java/run/attraction/api/v1/archive/AuditableEntity.java
  src/main/java/run/attraction/api/v1/auth/provider/google/GoogleOAuthService.java
  src/main/java/run/attraction/api/v1/auth/service/helper/JoinHelper.java
  src/main/java/run/attraction/api/v1/mypage/service/archive/article/MypageArticleServiceImpl.java
  src/main/java/run/attraction/api/v1/user/User.java
  src/main/java/run/attraction/api/v1/user/UserDetail.java
Labels: feat

#88 style: @Transactional 위치 수정
  src/main/java/run/attraction/api/v1/mypage/service/MypageService.java
  src/main/java/run/attraction/api/v1/mypage/service/archive/newsletter/MypageNewsletterServiceImpl.java
  src/main/java/run/attraction/api/v1/mypage/service/user/MypageUserServiceImpl.java
Labels: chore

#89 style: 이름 통일 name=>nickname
  src/main/java/run/attraction/api/v1/mypage/service/dto/userDetail/UserDetailDto.java
  src/main/java/run/attraction/api/v1/mypage/service/user/MypageUserServiceImpl.java
Labels: chore

#90 [ATR-226] : Article/AdminArticle entity 수정
  src/main/java/run/attraction/api/v1/archive/AdminArticle.java
  src/main/java/run/attraction/api/v1/archive/Article.java
Labels: feat

#91 [ATR-226] feat: Article/AdminArticle entity 수정 (#90)
  src/main/java/run/attraction/api/v1/archive/AdminArticle.java
  src/main/java/run/attraction/api/v1/archive/Article.java
Labels: feat

#92 [ATR - 241] feat: 유저가 구독한 뉴스레터 카테고리 저장
  src/main/java/run/attraction/api/v1/archive/service/ArchiveService.java
  src/main/java/run/attraction/api/v1/introduction/UserSubscribedNewsletterCategory.java
  src/main/java/run/attraction/api/v1/introduction/repository/UserSubscribedNewsletterCategoryRepository.java
Labels: feat

#93 Dev
  src/main/java/run/attraction/api/v1/archive/service/ArchiveService.java
  src/main/java/run/attraction/api/v1/auth/controller/AuthController.java
  src/main/java/run/attraction/api/v1/introduction/UserSubscribedNewsletterCategory.java
  src/main/java/run/attraction/api/v1/introduction/repository/UserSubscribedNewsletterCategoryRepository.java
Labels: feat

#94 [ATR-243] feat: 유저가 구독한 뉴스레터의 카테고리만 가져오기
  src/main/java/run/attraction/api/v1/archive/controller/ArchiveController.java
  src/main/java/run/attraction/api/v1/archive/service/ArchiveService.java
Labels: feat

#95 [ATR-243] feat: 유저가 구독한 뉴스레터의 카테고리만 가져오기 (#94)
  src/main/java/run/attraction/api/v1/archive/controller/ArchiveController.java
  src/main/java/run/attraction/api/v1/archive/service/ArchiveService.java
  src/main/resources/data.sql
Labels: feat

#96 [ATR - 244] fix: subscribe entity가 제대로 생성되지 않는 문제 수정
  src/main/java/run/attraction/api/v1/archive/Subscribe.java
  src/main/java/run/attraction/api/v1/archive/service/ArchiveService.java
Labels: bug

#99 [ATR-246] feat: 유저가 url로 바로 들어왔을 때 아티클 볼수있도록 API 기능 구현
  src/main/java/run/attraction/api/v1/archive/controller/ArchiveController.java
  src/main/java/run/attraction/api/v1/archive/repository/ArticleRepositoryCustom.java
  src/main/java/run/attraction/api/v1/archive/repository/ArticleRepositoryImpl.java
  src/main/java/run/attraction/api/v1/archive/service/ArchiveService.java
  src/main/java/run/attraction/api/v1/introduction/exception/ErrorMessages.java
Labels: feat

#100 [ATR-246] feat: 유저가 url로 바로 들어왔을 때 아티클 볼수있도록 API 기능 구현 (#99)
  src/main/java/run/attraction/api/v1/archive/controller/ArchiveController.java
  src/main/java/run/attraction/api/v1/archive/repository/ArticleRepositoryCustom.java
  src/main/java/run/attraction/api/v1/archive/repository/ArticleRepositoryImpl.java
  src/main/java/run/attraction/api/v1/archive/service/ArchiveService.java
  src/main/java/run/attraction/api/v1/introduction/exception/ErrorMessages.java
Labels: feat

#104 [ATR-254] fix: 라벨, 필터 등록시 409 문제
  src/main/java/run/attraction/api/v1/auth/token/repository/GoogleRefreshTokenRepository.java
  src/main/java/run/attraction/api/v1/gmail/GmailClient.java
Labels: bug

#106 [ATR-255] feat: 아티클 필터 수정
  src/main/java/run/attraction/api/v1/archive/controller/ArchiveController.java
  src/main/java/run/attraction/api/v1/archive/dto/request/UserArticlesRequest.java
  src/main/java/run/attraction/api/v1/archive/repository/ArticleRepositoryImpl.java
  src/main/resources/data.sql
Labels: feat

#107 [ATR-255] feat: 아티클 필터 수정 (#106)
  src/main/java/run/attraction/api/v1/archive/controller/ArchiveController.java
  src/main/java/run/attraction/api/v1/archive/dto/request/UserArticlesRequest.java
  src/main/java/run/attraction/api/v1/archive/repository/ArticleRepositoryImpl.java
  src/main/resources/data.sql
Labels: feat

#108 [ATR-257] feat: Transactional 동시성 문제 임시 해결 (DB Lock)
  src/main/java/run/attraction/api/v1/mypage/service/MypageService.java
  src/main/java/run/attraction/api/v1/mypage/service/user/MypageUserServiceImpl.java
  src/main/java/run/attraction/api/v1/user/repository/UserDetailRepository.java
Labels: feat

#110 style: readBox 변수명 변경 percentage-> readPercentage
  src/main/java/run/attraction/api/v1/archive/ReadBox.java
  src/main/java/run/attraction/api/v1/archive/dto/ArticleDTO.java
  src/main/java/run/attraction/api/v1/archive/repository/ArticleRepository.java
  src/main/java/run/attraction/api/v1/archive/repository/ArticleRepositoryImpl.java
  src/main/java/run/attraction/api/v1/archive/repository/ReadBoxRepository.java
  src/main/java/run/attraction/api/v1/archive/service/ArchiveService.java
  src/main/java/run/attraction/api/v1/mypage/service/archive/article/MypageArticleServiceImpl.java
  src/main/resources/data.sql
Labels: style

#111 style: 오타 수정
  src/main/java/run/attraction/api/v1/archive/ReadBox.java
  src/main/java/run/attraction/api/v1/archive/controller/ArchiveController.java
  src/main/java/run/attraction/api/v1/archive/dto/ArticleDTO.java
  src/main/java/run/attraction/api/v1/archive/dto/NewsletterDTO.java
  src/main/java/run/attraction/api/v1/archive/repository/ReadBoxRepository.java
  src/main/java/run/attraction/api/v1/archive/service/ArchiveService.java
Labels: style

#112 [ATR-260] fix: 정렬이 반대로 되는 오류 수정
  src/main/java/run/attraction/api/v1/archive/dto/request/UserArticlesRequest.java
  src/main/java/run/attraction/api/v1/archive/service/ArchiveService.java
Labels: bug

#113 [ATR-261] fix: readingTime = 0 인 경우도 반영
  src/main/java/run/attraction/api/v1/home/service/dto/article/ArticleDetailDto.java
Labels: bug

#114 [ATR-262] feat: nickname validator 생성 및 적용
  src/main/java/run/attraction/api/v1/auth/controller/AuthController.java
  src/main/java/run/attraction/api/v1/auth/service/AuthService.java
  src/main/java/run/attraction/api/v1/auth/service/helper/JoinHelper.java
  src/main/java/run/attraction/api/v1/mypage/controller/MypageController.java
  src/main/java/run/attraction/api/v1/mypage/service/user/MypageUserServiceImpl.java
  src/main/java/run/attraction/api/v1/user/UserDetail.java
  src/main/java/run/attraction/api/v1/user/validator/exception/InvalidNicknameException.java
  src/main/java/run/attraction/api/v1/user/validator/exception/InvalidNicknameExceptionHandler.java
  src/main/java/run/attraction/api/v1/user/validator/nickname/EnglishValidator.java
  src/main/java/run/attraction/api/v1/user/validator/nickname/KoreanValidator.java
  src/main/java/run/attraction/api/v1/user/validator/nickname/NicknameValidator.java
  src/main/java/run/attraction/api/v1/user/validator/nickname/NumberValidator.java
  src/main/java/run/attraction/api/v1/user/validator/nickname/SpecialValidator.java
  src/test/java/run/attraction/api/v1/user/validator/NicknameValidatorTest.java
Labels: feat

#115 [ATR-211] feat: nickname Validator 적용 및 readingTime 관련 수정
  src/main/java/run/attraction/api/v1/auth/controller/AuthController.java
  src/main/java/run/attraction/api/v1/auth/service/AuthService.java
  src/main/java/run/attraction/api/v1/auth/service/helper/JoinHelper.java
  src/main/java/run/attraction/api/v1/home/service/dto/article/ArticleDetailDto.java
  src/main/java/run/attraction/api/v1/mypage/controller/MypageController.java
  src/main/java/run/attraction/api/v1/mypage/service/user/MypageUserServiceImpl.java
  src/main/java/run/attraction/api/v1/user/UserDetail.java
  src/main/java/run/attraction/api/v1/user/validator/exception/InvalidNicknameException.java
  src/main/java/run/attraction/api/v1/user/validator/exception/InvalidNicknameExceptionHandler.java
  src/main/java/run/attraction/api/v1/user/validator/nickname/EnglishValidator.java
  src/main/java/run/attraction/api/v1/user/validator/nickname/KoreanValidator.java
  src/main/java/run/attraction/api/v1/user/validator/nickname/NicknameValidator.java
  src/main/java/run/attraction/api/v1/user/validator/nickname/NumberValidator.java
  src/main/java/run/attraction/api/v1/user/validator/nickname/SpecialValidator.java
  src/test/java/run/attraction/api/v1/user/validator/NicknameValidatorTest.java
Labels: feat

#116 [ATR-275] chore: dev 브랜치에 pull request 할때 빌드 및 테스트 진행
  .github/workflows/pull_request.yml
Labels: chore

#118 chore: deploy.yml 잘못된 설정 수정
  .github/workflows/deploy.yml
Labels: chore

#119 chore: deploy.yml 파일 수정
  .github/workflows/deploy.yml
Labels: chore

#120 [ATR-274] feat: 닉네임 대소문자 구분 추가
  src/main/java/run/attraction/api/v1/mypage/service/user/MypageUserServiceImpl.java
  src/main/java/run/attraction/api/v1/user/UserDetail.java
Labels: feat

#121 [ATR-277] feat: DB TINYINT타입을 BOOLEAN 타입으로 변경
  src/main/java/run/attraction/api/v1/archive/AdminArticle.java
  src/main/java/run/attraction/api/v1/archive/Article.java
  src/main/java/run/attraction/api/v1/auth/token/GoogleRefreshToken.java
  src/main/java/run/attraction/api/v1/introduction/Newsletter.java
  src/main/java/run/attraction/api/v1/user/User.java
Labels: feat

#123 [ATR-268] test: 마이페이지 테스트 코드 추가
  build.gradle
  src/main/java/run/attraction/api/v1/mypage/controller/MypageController.java
  src/test/java/run/attraction/api/v1/introduction/CategoryTest.java
  src/test/java/run/attraction/api/v1/mypage/service/archive/MypageArticleServiceTest.java
  src/test/java/run/attraction/api/v1/mypage/service/archive/MypageNewsletterSerivceTest.java
  src/test/java/run/attraction/api/v1/mypage/service/calendar/MypageCalendarServiceTest.java
  src/test/java/run/attraction/api/v1/mypage/service/user/MypageUserServiceTest.java
  src/test/java/run/attraction/api/v1/repository/NewsletterRepositoryTest.java
  src/test/java/run/attraction/api/v1/user/validator/NicknameValidatorTest.java
  src/test/resources/data-h2.sql
Labels: feat

#124 feat: thumbnail/content url prefix 추가
  src/main/java/run/attraction/api/v1/archive/AdminArticle.java
  src/main/java/run/attraction/api/v1/archive/Article.java
  src/main/java/run/attraction/api/v1/archive/dto/ArticleDTO.java
  src/main/java/run/attraction/api/v1/auth/token/GoogleRefreshToken.java
  src/main/java/run/attraction/api/v1/introduction/Newsletter.java
  src/main/java/run/attraction/api/v1/user/User.java
Labels: feat

#125 feat: thumbnail/content url prefix 추가
  src/main/java/run/attraction/api/v1/introduction/dto/response/PreviousArticleResponse.java
Labels: feat

#126 fix: 오타 수정
  src/main/java/run/attraction/api/v1/archive/dto/ArticleDTO.java
  src/main/java/run/attraction/api/v1/introduction/dto/response/PreviousArticleResponse.java
Labels: bug

#127 [ATR-267] test: NewsletterRepository 테스트 추가
  .github/workflows/pull_request.yml
  build.gradle
  src/main/java/run/attraction/api/v1/introduction/UserSubscribedNewsletterCategory.java
  src/test/java/run/attraction/api/v1/introduction/repository/NewsletterRepositoryTest.java
Labels: test

#128 [ATR-289] test: UserSubscribedNewsletterCategoryRepository 테스트 추가
  src/test/java/run/attraction/api/v1/introduction/repository/UserSubscribedNewsletterCategoryRepositoryTest.java
Labels: test

#129 [ATR-282] feat: 통계 테이블 생성
  build.gradle
  src/main/java/run/attraction/api/v1/statistics/AgeGroup.java
  src/main/java/run/attraction/api/v1/statistics/NewsletterEvent.java
  src/main/java/run/attraction/api/v1/statistics/repository/NewsletterEventRepository.java
  src/test/java/run/attraction/api/v1/statistics/AgeGroupTest.java
  src/test/java/run/attraction/api/v1/statistics/NewsletterEventRepositoryTest.java
  src/test/resources/data-h2.sql
Labels: feat

#132 [ATR-284] feat: 다독 랭킹 시스템 구현
  src/main/java/run/attraction/api/v1/archive/repository/ReadBoxRepository.java
  src/main/java/run/attraction/api/v1/rank/ExtensiveRank.java
  src/main/java/run/attraction/api/v1/rank/controller/RankController.java
  src/main/java/run/attraction/api/v1/rank/repository/ExtensiveRankRepository.java
  src/main/java/run/attraction/api/v1/rank/service/RankCalculator.java
  src/main/java/run/attraction/api/v1/rank/service/RankService.java
  src/main/java/run/attraction/api/v1/rank/service/dto/ExtensiveRankResponseDto.java
  src/main/java/run/attraction/api/v1/rank/service/dto/RankDetailDto.java
  src/main/java/run/attraction/api/v1/user/repository/UserRepository.java
Labels: feat

#133 [ATR-283] feat: 랭킹 시스템 구현 (다독 랭크)
  src/main/java/run/attraction/api/v1/archive/repository/ReadBoxRepository.java
  src/main/java/run/attraction/api/v1/rank/ExtensiveRank.java
  src/main/java/run/attraction/api/v1/rank/controller/RankController.java
  src/main/java/run/attraction/api/v1/rank/repository/ExtensiveRankRepository.java
  src/main/java/run/attraction/api/v1/rank/service/RankCalculator.java
  src/main/java/run/attraction/api/v1/rank/service/RankService.java
  src/main/java/run/attraction/api/v1/rank/service/dto/ExtensiveRankResponseDto.java
  src/main/java/run/attraction/api/v1/rank/service/dto/RankDetailDto.java
  src/main/java/run/attraction/api/v1/user/repository/UserRepository.java
Labels: feat

#134 Feature/atr 298 occupation statistics
  src/main/java/run/attraction/api/v1/archive/repository/ReadBoxRepository.java
  src/main/java/run/attraction/api/v1/rank/service/RankCalculator.java
  src/main/java/run/attraction/api/v1/statistics/OccupationStatistics.java
  src/main/java/run/attraction/api/v1/statistics/controller/StatisticsController.java
  src/main/java/run/attraction/api/v1/statistics/repository/NewsletterEventRepository.java
  src/main/java/run/attraction/api/v1/statistics/repository/OccupationStatisticsRepository.java
  src/main/java/run/attraction/api/v1/statistics/service/StatisticsService.java
  src/main/java/run/attraction/api/v1/statistics/service/occupation/OccupationStatisticsCalculator.java
Labels: feat

#135 [ATR-299] feat: 연령별 통계 시스템 구현
  src/main/java/run/attraction/api/v1/statistics/AgeGroupStatistics.java
  src/main/java/run/attraction/api/v1/statistics/controller/StatisticsController.java
  src/main/java/run/attraction/api/v1/statistics/repository/AgeGroupStatisticsRepository.java
  src/main/java/run/attraction/api/v1/statistics/repository/NewsletterEventRepository.java
  src/main/java/run/attraction/api/v1/statistics/service/StatisticsService.java
  src/main/java/run/attraction/api/v1/statistics/service/ageGroup/AgeGroupStatisticsCalculator.java
Labels: feat

#136 [ATR-313] feat: bookmark API 추가
  src/main/java/run/attraction/api/v1/archive/repository/ArticleRepository.java
  src/main/java/run/attraction/api/v1/archive/repository/ArticleRepositoryCustom.java
  src/main/java/run/attraction/api/v1/archive/repository/ArticleRepositoryImpl.java
  src/main/java/run/attraction/api/v1/bookmark/Bookmark.java
  src/main/java/run/attraction/api/v1/bookmark/controller/BookmarkController.java
  src/main/java/run/attraction/api/v1/bookmark/dto/BookmarkArticleRequest.java
  src/main/java/run/attraction/api/v1/bookmark/exception/BookmarkExceptionHandler.java
  src/main/java/run/attraction/api/v1/bookmark/repository/BookmarkRepository.java
  src/main/java/run/attraction/api/v1/bookmark/service/BookmarkService.java
  src/main/java/run/attraction/api/v1/introduction/exception/ErrorMessages.java
  src/test/java/run/attraction/api/v1/bookmark/repository/BookmarkRepositoryTest.java
  src/test/java/run/attraction/api/v1/bookmark/service/BookmarkServiceTest.java
  src/test/resources/sql/bookmark/bookmark-service-test-data.sql
Labels: feat

#138 [ATR-314] feat: login시 사용자 정보 메시지 큐에 저장
  build.gradle
  src/main/java/run/attraction/api/v1/archive/controller/ArchiveController.java
  src/main/java/run/attraction/api/v1/auth/service/helper/AuthProviderAndTokenHelper.java
  src/main/java/run/attraction/api/v1/gmail/GmailApiAccessException.java
  src/main/java/run/attraction/api/v1/gmail/GmailClient.java
  src/main/java/run/attraction/api/v1/gmail/GoogleClientSecretsNotLoadedException.java
  src/main/java/run/attraction/api/v1/mail/UserLoggedEvent.java
  src/main/java/run/attraction/api/v1/mail/UserMailEventHandler.java
  src/main/java/run/attraction/api/v1/mail/config/KafkaProducerConfig.java
Labels: refactor, feat

#139 [ATR-284] feat: 다독 랭킹 시스템 수정
  src/main/java/run/attraction/api/v1/archive/repository/ReadBoxRepository.java
Labels: feat

#140 [ATR-315] feat: 구독시 사용자 정보와 뉴스레터 이메일을 메시지 큐에 저장
  src/main/java/run/attraction/api/v1/archive/controller/ArchiveController.java
  src/main/java/run/attraction/api/v1/auth/config/AuthProviderConfig.java
  src/main/java/run/attraction/api/v1/auth/provider/AuthProvider.java
  src/main/java/run/attraction/api/v1/auth/service/helper/AuthProviderAndTokenHelper.java
  src/main/java/run/attraction/api/v1/auth/token/dto/UserGmailToken.java
  src/main/java/run/attraction/api/v1/auth/token/service/GoogleTokenService.java
  src/main/java/run/attraction/api/v1/gmail/config/KafkaProducerConfig.java
  src/main/java/run/attraction/api/v1/gmail/dto/UserGmailDto.java
  src/main/java/run/attraction/api/v1/gmail/entity/GoogleRefreshToken.java
  src/main/java/run/attraction/api/v1/gmail/event/UserLoggedEvent.java
  src/main/java/run/attraction/api/v1/gmail/event/UserMailEventHandler.java
  src/main/java/run/attraction/api/v1/gmail/event/UserSubscribedEvent.java
  src/main/java/run/attraction/api/v1/gmail/repository/GoogleRefreshTokenRepository.java
  src/main/java/run/attraction/api/v1/gmail/service/GmailService.java
Labels: refactor, feat

#142 [ATR-271] feat: 닉네임 Validator 수정 및 마이페이지 테스트 코드 추가
  build.gradle
  src/main/java/run/attraction/api/v1/mypage/controller/MypageController.java
  src/main/java/run/attraction/api/v1/mypage/service/user/MypageUserServiceImpl.java
  src/main/java/run/attraction/api/v1/user/UserDetail.java
  src/test/java/run/attraction/api/v1/introduction/CategoryTest.java
  src/test/java/run/attraction/api/v1/mypage/service/archive/MypageArticleServiceTest.java
  src/test/java/run/attraction/api/v1/mypage/service/archive/MypageNewsletterSerivceTest.java
  src/test/java/run/attraction/api/v1/mypage/service/calendar/MypageCalendarServiceTest.java
  src/test/java/run/attraction/api/v1/mypage/service/user/MypageUserServiceTest.java
  src/test/java/run/attraction/api/v1/repository/NewsletterRepositoryTest.java
  src/test/java/run/attraction/api/v1/user/validator/NicknameValidatorTest.java
  src/test/resources/data-h2.sql
Labels: feat

#143 [ATR-281] 통계 및 랭킹 시스템 구현
  src/main/java/run/attraction/api/v1/archive/repository/ReadBoxRepository.java
  src/main/java/run/attraction/api/v1/rank/ConsistencyRank.java
  src/main/java/run/attraction/api/v1/rank/ExtensiveRank.java
  src/main/java/run/attraction/api/v1/rank/Rank.java
  src/main/java/run/attraction/api/v1/rank/ReadBoxEvent.java
  src/main/java/run/attraction/api/v1/rank/controller/RankController.java
  src/main/java/run/attraction/api/v1/rank/repository/ConsistencyRankRepository.java
  src/main/java/run/attraction/api/v1/rank/repository/ExtensiveRankRepository.java
  src/main/java/run/attraction/api/v1/rank/repository/ReadBoxEventRepository.java
  src/main/java/run/attraction/api/v1/rank/service/RankService.java
  src/main/java/run/attraction/api/v1/rank/service/calculator/ConsistencyRankCalculator.java
  src/main/java/run/attraction/api/v1/rank/service/calculator/ExtensiveRankCalculator.java
  src/main/java/run/attraction/api/v1/rank/service/dto/RankDetailDto.java
  src/main/java/run/attraction/api/v1/rank/service/dto/RankResponseDto.java
  src/main/java/run/attraction/api/v1/statistics/AgeGroup.java
  src/main/java/run/attraction/api/v1/statistics/AgeGroupStatistics.java
  src/main/java/run/attraction/api/v1/statistics/NewsletterEvent.java
  src/main/java/run/attraction/api/v1/statistics/OccupationStatistics.java
  src/main/java/run/attraction/api/v1/statistics/controller/StatisticsController.java
  src/main/java/run/attraction/api/v1/statistics/repository/AgeGroupStatisticsRepository.java
  src/main/java/run/attraction/api/v1/statistics/repository/NewsletterEventRepository.java
  src/main/java/run/attraction/api/v1/statistics/repository/OccupationStatisticsRepository.java
  src/main/java/run/attraction/api/v1/statistics/service/StatisticsService.java
  src/main/java/run/attraction/api/v1/statistics/service/ageGroup/AgeGroupStatisticsCalculator.java
  src/main/java/run/attraction/api/v1/statistics/service/occupation/OccupationStatisticsCalculator.java
  src/main/java/run/attraction/api/v1/user/repository/UserRepository.java
  src/test/java/run/attraction/api/v1/statistics/AgeGroupTest.java
  src/test/java/run/attraction/api/v1/statistics/NewsletterEventRepositoryTest.java
  src/test/resources/data-h2.sql
Labels: feat

#145 [ATR-283] chore: API 이름 통일
  src/main/java/run/attraction/api/v1/rank/controller/RankController.java
  src/main/java/run/attraction/api/v1/rank/service/dto/ConsistencyRankResponseDto.java
  src/main/java/run/attraction/api/v1/rank/service/dto/ExtensiveRankResponseDto.java
  src/main/java/run/attraction/api/v1/rank/service/dto/RankResponseDto.java
Labels: chore

#146 [ATR-326] feat: 마이페이지 개인설정 API 분리
  src/main/java/run/attraction/api/v1/mypage/controller/MypageController.java
  src/main/java/run/attraction/api/v1/mypage/service/MypageService.java
  src/main/java/run/attraction/api/v1/mypage/service/dto/userDetail/UpdateBackgroundImgRequestDto.java
  src/main/java/run/attraction/api/v1/mypage/service/dto/userDetail/UpdateImgRequestDto.java
  src/main/java/run/attraction/api/v1/mypage/service/dto/userDetail/UpdateInterestRequestDto.java
  src/main/java/run/attraction/api/v1/mypage/service/dto/userDetail/UpdateNicknameRequestDto.java
  src/main/java/run/attraction/api/v1/mypage/service/dto/userDetail/UpdateOccupationRequestDto.java
  src/main/java/run/attraction/api/v1/mypage/service/dto/userDetail/UpdateUserDetailDto.java
  src/main/java/run/attraction/api/v1/mypage/service/dto/userDetail/UpdateUserDetailRequestDto.java
  src/main/java/run/attraction/api/v1/mypage/service/dto/userDetail/UpdateUserExpirationRequestDto.java
  src/main/java/run/attraction/api/v1/mypage/service/user/MypageUserService.java
  src/main/java/run/attraction/api/v1/mypage/service/user/MypageUserServiceImpl.java
  src/main/java/run/attraction/api/v1/user/repository/UserDetailRepository.java
Labels: feat

#147 [ATR-343] feat: 사용자 정보 반환 api 수정
  src/main/java/run/attraction/api/v1/mypage/service/dto/userDetail/UserDetailDto.java
  src/main/java/run/attraction/api/v1/mypage/service/user/MypageUserServiceImpl.java
  src/main/resources/data.sql
  src/test/java/run/attraction/api/v1/mypage/service/user/MypageUserServiceTest.java
Labels: feat

#148 [ATR-328] feat: 메인페이지 통합 검색 시스템 구현
  src/main/java/run/attraction/api/v1/archive/repository/ArticleRepository.java
  src/main/java/run/attraction/api/v1/home/controller/HomeController.java
  src/main/java/run/attraction/api/v1/home/service/HomeService.java
  src/main/java/run/attraction/api/v1/home/service/article/HomeArticleService.java
  src/main/java/run/attraction/api/v1/home/service/article/HomeArticleServiceImpl.java
  src/main/java/run/attraction/api/v1/home/service/newsletter/HomeNewsletterService.java
  src/main/java/run/attraction/api/v1/home/service/newsletter/HomeNewsletterServiceImpl.java
  src/main/java/run/attraction/api/v1/introduction/repository/NewsletterRepository.java
Labels: feat

#152 [ATR-327] feat: 메인페이지 통합검색 기능 추가
  src/main/java/run/attraction/api/v1/archive/repository/ArticleRepository.java
  src/main/java/run/attraction/api/v1/home/controller/HomeController.java
  src/main/java/run/attraction/api/v1/home/service/HomeService.java
  src/main/java/run/attraction/api/v1/home/service/article/HomeArticleService.java
  src/main/java/run/attraction/api/v1/home/service/article/HomeArticleServiceImpl.java
  src/main/java/run/attraction/api/v1/home/service/newsletter/HomeNewsletterService.java
  src/main/java/run/attraction/api/v1/home/service/newsletter/HomeNewsletterServiceImpl.java
  src/main/java/run/attraction/api/v1/introduction/repository/NewsletterRepository.java
  src/test/java/run/attraction/api/v1/statistics/NewsletterEventRepositoryTest.java
Labels: feat

#153 [ATR-271] feat: 마이페이지 개인설정 API 수정
  .github/workflows/pull_request.yml
  src/main/java/run/attraction/api/v1/introduction/UserSubscribedNewsletterCategory.java
  src/main/java/run/attraction/api/v1/mypage/controller/MypageController.java
  src/main/java/run/attraction/api/v1/mypage/service/MypageService.java
  src/main/java/run/attraction/api/v1/mypage/service/dto/userDetail/UpdateBackgroundImgRequestDto.java
  src/main/java/run/attraction/api/v1/mypage/service/dto/userDetail/UpdateImgRequestDto.java
  src/main/java/run/attraction/api/v1/mypage/service/dto/userDetail/UpdateInterestRequestDto.java
  src/main/java/run/attraction/api/v1/mypage/service/dto/userDetail/UpdateNicknameRequestDto.java
  src/main/java/run/attraction/api/v1/mypage/service/dto/userDetail/UpdateOccupationRequestDto.java
  src/main/java/run/attraction/api/v1/mypage/service/dto/userDetail/UpdateUserDetailDto.java
  src/main/java/run/attraction/api/v1/mypage/service/dto/userDetail/UpdateUserDetailRequestDto.java
  src/main/java/run/attraction/api/v1/mypage/service/dto/userDetail/UpdateUserExpirationRequestDto.java
  src/main/java/run/attraction/api/v1/mypage/service/dto/userDetail/UserDetailDto.java
  src/main/java/run/attraction/api/v1/mypage/service/user/MypageUserService.java
  src/main/java/run/attraction/api/v1/mypage/service/user/MypageUserServiceImpl.java
  src/main/java/run/attraction/api/v1/user/UserDetail.java
  src/main/java/run/attraction/api/v1/user/repository/UserDetailRepository.java
  src/main/resources/data.sql
  src/test/java/run/attraction/api/v1/mypage/service/user/MypageUserServiceTest.java
Labels: feat

#154 feat: 통합 검색 API 추가 및 개인설정 API 수정
  .github/workflows/deploy.yml
  .github/workflows/pull_request.yml
  build.gradle
  src/main/java/run/attraction/api/v1/archive/repository/ArticleRepository.java
  src/main/java/run/attraction/api/v1/home/controller/HomeController.java
  src/main/java/run/attraction/api/v1/home/service/HomeService.java
  src/main/java/run/attraction/api/v1/home/service/article/HomeArticleService.java
  src/main/java/run/attraction/api/v1/home/service/article/HomeArticleServiceImpl.java
  src/main/java/run/attraction/api/v1/home/service/newsletter/HomeNewsletterService.java
  src/main/java/run/attraction/api/v1/home/service/newsletter/HomeNewsletterServiceImpl.java
  src/main/java/run/attraction/api/v1/introduction/UserSubscribedNewsletterCategory.java
  src/main/java/run/attraction/api/v1/introduction/repository/NewsletterRepository.java
  src/main/java/run/attraction/api/v1/mypage/controller/MypageController.java
  src/main/java/run/attraction/api/v1/mypage/service/MypageService.java
  src/main/java/run/attraction/api/v1/mypage/service/dto/userDetail/UpdateBackgroundImgRequestDto.java
  src/main/java/run/attraction/api/v1/mypage/service/dto/userDetail/UpdateImgRequestDto.java
  src/main/java/run/attraction/api/v1/mypage/service/dto/userDetail/UpdateInterestRequestDto.java
  src/main/java/run/attraction/api/v1/mypage/service/dto/userDetail/UpdateNicknameRequestDto.java
  src/main/java/run/attraction/api/v1/mypage/service/dto/userDetail/UpdateOccupationRequestDto.java
  src/main/java/run/attraction/api/v1/mypage/service/dto/userDetail/UpdateUserDetailDto.java
  src/main/java/run/attraction/api/v1/mypage/service/dto/userDetail/UpdateUserDetailRequestDto.java
  src/main/java/run/attraction/api/v1/mypage/service/dto/userDetail/UpdateUserExpirationRequestDto.java
  src/main/java/run/attraction/api/v1/mypage/service/dto/userDetail/UserDetailDto.java
  src/main/java/run/attraction/api/v1/mypage/service/user/MypageUserService.java
  src/main/java/run/attraction/api/v1/mypage/service/user/MypageUserServiceImpl.java
  src/main/java/run/attraction/api/v1/user/UserDetail.java
  src/main/java/run/attraction/api/v1/user/repository/UserDetailRepository.java
  src/main/resources/data.sql
  src/test/java/run/attraction/api/v1/introduction/repository/NewsletterRepositoryTest.java
  src/test/java/run/attraction/api/v1/introduction/repository/UserSubscribedNewsletterCategoryRepositoryTest.java
  src/test/java/run/attraction/api/v1/mypage/service/user/MypageUserServiceTest.java
  src/test/java/run/attraction/api/v1/statistics/NewsletterEventRepositoryTest.java
Labels: feat

#155 [ATR-319] feat: 지난 아티클 상세 조회 API 구현
  src/main/java/run/attraction/api/v1/introduction/controller/IntroductionController.java
  src/main/java/run/attraction/api/v1/introduction/dto/response/PreviousArticleResponse.java
  src/main/java/run/attraction/api/v1/introduction/service/IntroductionService.java
Labels: feat

#156 [ATR-371] feat: 구독리스트에 뉴스레터 중복 추가 제한
  src/main/java/run/attraction/api/v1/archive/service/ArchiveService.java
  src/main/java/run/attraction/api/v1/introduction/exception/ErrorMessages.java
Labels: feat

#157 [ATR-373] feat: 글로벌 예외 처리 개선
  src/main/java/run/attraction/api/v1/introduction/exception/GlobalExceptionHandler.java
  src/test/java/run/attraction/api/v1/globalException/GlobalExceptionHandlerTest.java
  src/test/java/run/attraction/api/v1/globalException/TestController.java
Labels: feat

#160 Release
  src/main/java/run/attraction/api/v1/archive/service/ArchiveService.java
  src/main/java/run/attraction/api/v1/introduction/controller/IntroductionController.java
  src/main/java/run/attraction/api/v1/introduction/dto/response/PreviousArticleResponse.java
  src/main/java/run/attraction/api/v1/introduction/exception/ErrorMessages.java
  src/main/java/run/attraction/api/v1/introduction/exception/GlobalExceptionHandler.java
  src/main/java/run/attraction/api/v1/introduction/service/IntroductionService.java
  src/test/java/run/attraction/api/v1/globalException/GlobalExceptionHandlerTest.java
  src/test/java/run/attraction/api/v1/globalException/TestController.java
Labels: feat

#161 [ATR-337] feat: 글로벌 예외 처리 개선
  src/main/java/run/attraction/api/v1/exception/ErrorCode.java
  src/main/java/run/attraction/api/v1/exception/ErrorResponse.java
  src/main/java/run/attraction/api/v1/exception/GlobalExceptionHandler.java
  src/main/java/run/attraction/api/v1/introduction/exception/GlobalExceptionHandler.java
  src/test/java/run/attraction/api/v1/globalException/GlobalExceptionHandlerTest.java
  src/test/java/run/attraction/api/v1/globalException/TestController.java
Labels: feat

#163 [ATR-394] feat: 아티클 검색 DTO 수정
  src/main/java/run/attraction/api/v1/archive/repository/ArticleRepository.java
  src/main/java/run/attraction/api/v1/home/controller/HomeController.java
  src/main/java/run/attraction/api/v1/home/service/HomeService.java
  src/main/java/run/attraction/api/v1/home/service/article/HomeArticleService.java
  src/main/java/run/attraction/api/v1/home/service/article/HomeArticleServiceImpl.java
Labels: feat

#164 [ATR-394] feat: 아티클 검색 DTO 수정
  src/main/java/run/attraction/api/v1/archive/repository/ArticleRepository.java
  src/main/java/run/attraction/api/v1/home/controller/HomeController.java
  src/main/java/run/attraction/api/v1/home/service/HomeService.java
  src/main/java/run/attraction/api/v1/home/service/article/HomeArticleService.java
  src/main/java/run/attraction/api/v1/home/service/article/HomeArticleServiceImpl.java
Labels: feat

#165 [ATR-394] feat: 아티클 검색 DTO 추가 수정
  src/main/java/run/attraction/api/v1/archive/repository/ArticleRepository.java
  src/main/java/run/attraction/api/v1/home/controller/HomeController.java
  src/main/java/run/attraction/api/v1/home/service/HomeService.java
  src/main/java/run/attraction/api/v1/home/service/article/HomeArticleService.java
  src/main/java/run/attraction/api/v1/home/service/article/HomeArticleServiceImpl.java
  src/main/java/run/attraction/api/v1/home/service/dto/search/ArticleSearchDto.java
  src/main/java/run/attraction/api/v1/introduction/dto/response/PreviousArticleResponse.java
Labels: feat

#166 [ATR-394] feat: 아티클 검색 DTO 추가 수정
  src/main/java/run/attraction/api/v1/archive/repository/ArticleRepository.java
  src/main/java/run/attraction/api/v1/home/controller/HomeController.java
  src/main/java/run/attraction/api/v1/home/service/HomeService.java
  src/main/java/run/attraction/api/v1/home/service/article/HomeArticleService.java
  src/main/java/run/attraction/api/v1/home/service/article/HomeArticleServiceImpl.java
  src/main/java/run/attraction/api/v1/home/service/dto/search/ArticleSearchDto.java
  src/main/java/run/attraction/api/v1/introduction/dto/response/PreviousArticleResponse.java
Labels: feat

#167 [ATR-341] spring kafka support로 리팩터링
  build.gradle
  src/main/java/run/attraction/api/v1/auth/service/helper/AuthProviderAndTokenHelper.java
  src/main/java/run/attraction/api/v1/gmail/config/AsyncConfig.java
  src/main/java/run/attraction/api/v1/gmail/config/KafkaProducerConfig.java
  src/main/java/run/attraction/api/v1/gmail/config/ProducerProperties.java
  src/main/java/run/attraction/api/v1/gmail/config/SubscribeProducerListener.java
  src/main/java/run/attraction/api/v1/gmail/event/SubscribeVo.java
  src/main/java/run/attraction/api/v1/gmail/event/UserLoggedEvent.java
  src/main/java/run/attraction/api/v1/gmail/event/UserMailEventHandler.java
  src/main/java/run/attraction/api/v1/gmail/event/UserSubscribedEvent.java
  src/main/java/run/attraction/api/v1/gmail/service/GmailService.java
Labels: refactor

#169 [ATR-341] spring kafka support로 리팩터링
  build.gradle
  src/main/java/run/attraction/api/v1/auth/service/helper/AuthProviderAndTokenHelper.java
  src/main/java/run/attraction/api/v1/gmail/config/AsyncConfig.java
  src/main/java/run/attraction/api/v1/gmail/config/KafkaProducerConfig.java
  src/main/java/run/attraction/api/v1/gmail/config/ProducerProperties.java
  src/main/java/run/attraction/api/v1/gmail/config/SubscribeProducerListener.java
  src/main/java/run/attraction/api/v1/gmail/event/SubscribeVo.java
  src/main/java/run/attraction/api/v1/gmail/event/UserLoggedEvent.java
  src/main/java/run/attraction/api/v1/gmail/event/UserMailEventHandler.java
  src/main/java/run/attraction/api/v1/gmail/event/UserSubscribedEvent.java
  src/main/java/run/attraction/api/v1/gmail/service/GmailService.java
Labels: refactor, feat

#171 [ATR-401] feat: monitoring system
  .gitignore
  build.gradle
  src/main/java/run/attraction/api/v1/auth/controller/FaviconController.java
  src/main/java/run/attraction/api/v1/auth/filter/HttpLogMessage.java
  src/main/java/run/attraction/api/v1/auth/filter/RequestLogFilter.java
  src/main/java/run/attraction/api/v1/auth/service/helper/AuthProviderAndTokenHelper.java
  src/main/java/run/attraction/api/v1/gmail/config/AsyncConfig.java
  src/main/java/run/attraction/api/v1/gmail/config/KafkaProducerConfig.java
  src/main/java/run/attraction/api/v1/gmail/config/ProducerProperties.java
  src/main/java/run/attraction/api/v1/gmail/config/SubscribeProducerListener.java
  src/main/java/run/attraction/api/v1/gmail/event/SubscribeVo.java
  src/main/java/run/attraction/api/v1/gmail/event/UserLoggedEvent.java
  src/main/java/run/attraction/api/v1/gmail/event/UserMailEventHandler.java
  src/main/java/run/attraction/api/v1/gmail/event/UserSubscribedEvent.java
  src/main/java/run/attraction/api/v1/gmail/service/GmailService.java
  src/main/resources/log4j2.xml
Labels: feat

#172 [ATR-413] chore: github action 도커 볼륨을 aws 디렉토리와 마운트
  .github/workflows/deploy.yml
Labels: feat

#173 [ATR-413] chore: github action 도커 볼륨을 aws 디렉토리와 마운트 (#172)
  .github/workflows/deploy.yml
Labels: chore

#174 [ATR-412] feat: NewsletterEvent 저장 로직 추가
  src/main/java/run/attraction/api/v1/archive/repository/ArticleRepository.java
  src/main/java/run/attraction/api/v1/archive/service/ArchiveService.java
  src/main/java/run/attraction/api/v1/statistics/repository/NewsletterEventRepository.java
Labels: feat

#175 [ATR-415] feat: ReadBoxEvent 저장 로직 추가
  src/main/java/run/attraction/api/v1/archive/service/ArchiveService.java
  src/main/java/run/attraction/api/v1/rank/service/calculator/ConsistencyRankCalculator.java
  src/main/java/run/attraction/api/v1/statistics/controller/StatisticsController.java
  src/main/java/run/attraction/api/v1/statistics/service/StatisticsService.java
Labels: feat

#176 [ATR-418] 뉴스레터 소개페이지 수정
  src/main/java/run/attraction/api/v1/introduction/Category.java
  src/main/java/run/attraction/api/v1/introduction/Newsletter.java
  src/main/java/run/attraction/api/v1/introduction/dto/response/NewsletterResponse.java
  src/main/resources/data.sql
  src/test/java/run/attraction/api/v1/bookmark/service/BookmarkServiceTest.java
  src/test/java/run/attraction/api/v1/introduction/CategoryTest.java
  src/test/resources/sql/bookmark/bookmark-service-test-data.sql
  src/test/resources/sql/data-h2.sql
Labels: test, feat

#177 [ATR-418] 뉴스레터 소개페이지 수정
  src/main/java/run/attraction/api/v1/archive/repository/ArticleRepository.java
  src/main/java/run/attraction/api/v1/archive/service/ArchiveService.java
  src/main/java/run/attraction/api/v1/introduction/Category.java
  src/main/java/run/attraction/api/v1/introduction/Newsletter.java
  src/main/java/run/attraction/api/v1/introduction/dto/response/NewsletterResponse.java
  src/main/java/run/attraction/api/v1/rank/service/calculator/ConsistencyRankCalculator.java
  src/main/java/run/attraction/api/v1/statistics/controller/StatisticsController.java
  src/main/java/run/attraction/api/v1/statistics/repository/NewsletterEventRepository.java
  src/main/java/run/attraction/api/v1/statistics/service/StatisticsService.java
  src/main/resources/data.sql
  src/test/java/run/attraction/api/v1/bookmark/service/BookmarkServiceTest.java
  src/test/java/run/attraction/api/v1/introduction/CategoryTest.java
  src/test/resources/sql/bookmark/bookmark-service-test-data.sql
  src/test/resources/sql/data-h2.sql
Labels: test, feat

#178 chore: github action에 filebeat 도커 추가
  .github/workflows/deploy.yml
Labels: chore

#179 fix: filebeat docker 설정 변경
  .github/workflows/deploy.yml
Labels: bug, chore

#180 fix: filebeat 도커 컨테이너 종료후 재실행하도록 변경
  .github/workflows/deploy.yml
Labels: bug

#181 style: 오타 수정
  src/main/java/run/attraction/api/v1/introduction/Category.java
Labels: style

#182 style: 오타 수정
  src/test/java/run/attraction/api/v1/introduction/CategoryTest.java
Labels: style

#183 chore: github action deploy 파일 수정
  .github/workflows/deploy.yml
Labels: chore

#184 chore: filebeat docker 명령어 수정
  .github/workflows/deploy.yml
Labels: chore

#185 [ATR-418] feat: findArticlesByUserId 메서드 수정
  src/main/java/run/attraction/api/v1/archive/repository/ArticleRepositoryCustom.java
  src/main/java/run/attraction/api/v1/archive/repository/ArticleRepositoryImpl.java
  src/main/java/run/attraction/api/v1/archive/service/ArchiveService.java
  src/main/resources/data.sql
  src/test/java/run/attraction/api/v1/bookmark/service/BookmarkServiceTest.java
Labels: feat

#186 [ATR-441] feat: findArticleByUserEmailAndArticleId 메서드 수정
  src/main/java/run/attraction/api/v1/archive/repository/ArticleRepositoryImpl.java
Labels: feat

#187 remove: AdminArticle 엔티티 및 레포지토리 삭제
  src/main/java/run/attraction/api/v1/archive/AdminArticle.java
  src/main/java/run/attraction/api/v1/archive/repository/AdminArticleRepository.java
  src/main/java/run/attraction/api/v1/archive/repository/ArticleRepository.java
  src/main/java/run/attraction/api/v1/introduction/dto/response/PreviousArticleResponse.java
  src/main/java/run/attraction/api/v1/introduction/service/IntroductionService.java
Labels: remove

#188 [ATR-439] 어드민 아티클 삭제 및 관련 로직 수정
  src/main/java/run/attraction/api/v1/archive/AdminArticle.java
  src/main/java/run/attraction/api/v1/archive/repository/AdminArticleRepository.java
  src/main/java/run/attraction/api/v1/archive/repository/ArticleRepository.java
  src/main/java/run/attraction/api/v1/archive/repository/ArticleRepositoryCustom.java
  src/main/java/run/attraction/api/v1/archive/repository/ArticleRepositoryImpl.java
  src/main/java/run/attraction/api/v1/archive/service/ArchiveService.java
  src/main/java/run/attraction/api/v1/introduction/dto/response/PreviousArticleResponse.java
  src/main/java/run/attraction/api/v1/introduction/service/IntroductionService.java
  src/main/resources/data.sql
  src/test/java/run/attraction/api/v1/bookmark/service/BookmarkServiceTest.java
Labels: remove, feat

#189 [ATR-447] feat: 마이페이지 최근 읽은 아티클 로직 수정
  src/main/java/run/attraction/api/v1/archive/repository/ArticleRepositoryCustom.java
  src/main/java/run/attraction/api/v1/archive/repository/ArticleRepositoryImpl.java
  src/main/java/run/attraction/api/v1/mypage/controller/MypageController.java
  src/main/java/run/attraction/api/v1/mypage/service/MypageService.java
  src/main/java/run/attraction/api/v1/mypage/service/archive/article/MypageArticleService.java
  src/main/java/run/attraction/api/v1/mypage/service/archive/article/MypageArticleServiceImpl.java
  src/main/java/run/attraction/api/v1/mypage/service/dto/archive/article/RecentArticleNewsletterDto.java
  src/main/java/run/attraction/api/v1/mypage/service/dto/archive/article/RecentArticlesDto.java
  src/main/java/run/attraction/api/v1/mypage/service/dto/archive/article/RecentArticlesResponseDto.java
Labels: feat

#190 [ATR-447] feat: 마이페이지 최근 읽은 아티클 로직 수정
  src/main/java/run/attraction/api/v1/archive/repository/ArticleRepositoryCustom.java
  src/main/java/run/attraction/api/v1/archive/repository/ArticleRepositoryImpl.java
  src/main/java/run/attraction/api/v1/mypage/controller/MypageController.java
  src/main/java/run/attraction/api/v1/mypage/service/MypageService.java
  src/main/java/run/attraction/api/v1/mypage/service/archive/article/MypageArticleService.java
  src/main/java/run/attraction/api/v1/mypage/service/archive/article/MypageArticleServiceImpl.java
  src/main/java/run/attraction/api/v1/mypage/service/dto/archive/article/RecentArticleNewsletterDto.java
  src/main/java/run/attraction/api/v1/mypage/service/dto/archive/article/RecentArticlesDto.java
  src/main/java/run/attraction/api/v1/mypage/service/dto/archive/article/RecentArticlesResponseDto.java
  src/main/resources/data.sql
Labels: feat

#191 [ATR-432] feat: 세션 로그인 적용
  src/main/java/run/attraction/api/v1/auth/config/SecurityConfig.java
  src/main/java/run/attraction/api/v1/auth/controller/AuthController.java
  src/main/java/run/attraction/api/v1/auth/filter/JwtAuthenticationFilter.java
  src/main/java/run/attraction/api/v1/auth/provider/AuthProvider.java
  src/main/java/run/attraction/api/v1/auth/provider/google/GoogleOAuthService.java
  src/main/java/run/attraction/api/v1/auth/service/AuthService.java
  src/main/java/run/attraction/api/v1/auth/service/dto/UserStateDto.java
  src/main/java/run/attraction/api/v1/auth/service/dto/login/LoginResponseDto.java
  src/main/java/run/attraction/api/v1/auth/service/helper/AuthProviderAndTokenHelper.java
  src/main/java/run/attraction/api/v1/auth/service/helper/JoinHelper.java
  src/main/java/run/attraction/api/v1/auth/service/helper/LoginHelper.java
  src/main/java/run/attraction/api/v1/auth/session/SessionService.java
  src/main/java/run/attraction/api/v1/auth/token/CookieTokenSetter.java
  src/main/java/run/attraction/api/v1/auth/token/LogoutAccessToken.java
  src/main/java/run/attraction/api/v1/auth/token/RefreshToken.java
  src/main/java/run/attraction/api/v1/auth/token/exception/InvalidTokenException.java
  src/main/java/run/attraction/api/v1/auth/token/exception/TokenExpirationException.java
  src/main/java/run/attraction/api/v1/auth/token/exception/TokenNotFoundException.java
  src/main/java/run/attraction/api/v1/auth/token/jwt/JwtService.java
  src/main/java/run/attraction/api/v1/auth/token/jwt/JwtServiceImpl.java
  src/main/java/run/attraction/api/v1/auth/token/repository/LogoutAccessTokenRepository.java
  src/main/java/run/attraction/api/v1/auth/token/repository/RefreshTokenRepository.java
Labels: feat

#192 [ATR-448] feat: 회원 탈퇴 로직 추가
  src/main/java/run/attraction/api/v1/auth/service/helper/LoginHelper.java
  src/main/java/run/attraction/api/v1/mypage/controller/MypageController.java
  src/main/java/run/attraction/api/v1/mypage/service/MypageService.java
  src/main/java/run/attraction/api/v1/mypage/service/user/MypageUserService.java
  src/main/java/run/attraction/api/v1/mypage/service/user/MypageUserServiceImpl.java
  src/main/java/run/attraction/api/v1/user/User.java
Labels: feat

#193 [ATR-449] feat: 최근 받은 아티클 로직 수정 - 메인페이지
  src/main/java/run/attraction/api/v1/archive/repository/ArticleRepository.java
  src/main/java/run/attraction/api/v1/archive/repository/ArticleRepositoryCustom.java
  src/main/java/run/attraction/api/v1/archive/repository/ArticleRepositoryImpl.java
  src/main/java/run/attraction/api/v1/home/controller/HomeController.java
  src/main/java/run/attraction/api/v1/home/service/HomeService.java
  src/main/java/run/attraction/api/v1/home/service/article/HomeArticleService.java
  src/main/java/run/attraction/api/v1/home/service/article/HomeArticleServiceImpl.java
  src/main/java/run/attraction/api/v1/home/service/dto/article/ReceivedArticleNewsletterDto.java
  src/main/java/run/attraction/api/v1/home/service/dto/article/ReceivedArticlesDto.java
  src/main/java/run/attraction/api/v1/home/service/dto/article/ReceivedArticlesResponseDto.java
Labels: feat

#194 [ATR-449] feat: 최근 받은 아티클 로직 수정 (#193)
  src/main/java/run/attraction/api/v1/archive/repository/ArticleRepository.java
  src/main/java/run/attraction/api/v1/archive/repository/ArticleRepositoryCustom.java
  src/main/java/run/attraction/api/v1/archive/repository/ArticleRepositoryImpl.java
  src/main/java/run/attraction/api/v1/home/controller/HomeController.java
  src/main/java/run/attraction/api/v1/home/service/HomeService.java
  src/main/java/run/attraction/api/v1/home/service/article/HomeArticleService.java
  src/main/java/run/attraction/api/v1/home/service/article/HomeArticleServiceImpl.java
  src/main/java/run/attraction/api/v1/home/service/dto/article/ReceivedArticleNewsletterDto.java
  src/main/java/run/attraction/api/v1/home/service/dto/article/ReceivedArticlesDto.java
  src/main/java/run/attraction/api/v1/home/service/dto/article/ReceivedArticlesResponseDto.java
Labels: feat

#196 feat: 세션 로그인 적용 및 회원 탈퇴 로직 추가
  src/main/java/run/attraction/api/v1/auth/config/SecurityConfig.java
  src/main/java/run/attraction/api/v1/auth/controller/AuthController.java
  src/main/java/run/attraction/api/v1/auth/filter/JwtAuthenticationFilter.java
  src/main/java/run/attraction/api/v1/auth/provider/AuthProvider.java
  src/main/java/run/attraction/api/v1/auth/provider/google/GoogleOAuthService.java
  src/main/java/run/attraction/api/v1/auth/service/AuthService.java
  src/main/java/run/attraction/api/v1/auth/service/dto/UserStateDto.java
  src/main/java/run/attraction/api/v1/auth/service/dto/login/LoginResponseDto.java
  src/main/java/run/attraction/api/v1/auth/service/helper/AuthProviderAndTokenHelper.java
  src/main/java/run/attraction/api/v1/auth/service/helper/JoinHelper.java
  src/main/java/run/attraction/api/v1/auth/service/helper/LoginHelper.java
  src/main/java/run/attraction/api/v1/auth/session/SessionService.java
  src/main/java/run/attraction/api/v1/auth/token/CookieTokenSetter.java
  src/main/java/run/attraction/api/v1/auth/token/LogoutAccessToken.java
  src/main/java/run/attraction/api/v1/auth/token/RefreshToken.java
  src/main/java/run/attraction/api/v1/auth/token/exception/InvalidTokenException.java
  src/main/java/run/attraction/api/v1/auth/token/exception/TokenExpirationException.java
  src/main/java/run/attraction/api/v1/auth/token/exception/TokenNotFoundException.java
  src/main/java/run/attraction/api/v1/auth/token/jwt/JwtService.java
  src/main/java/run/attraction/api/v1/auth/token/jwt/JwtServiceImpl.java
  src/main/java/run/attraction/api/v1/auth/token/repository/LogoutAccessTokenRepository.java
  src/main/java/run/attraction/api/v1/auth/token/repository/RefreshTokenRepository.java
  src/main/java/run/attraction/api/v1/home/service/dto/article/ArticleDetailDto.java
  src/main/java/run/attraction/api/v1/home/service/dto/article/ReceivedArticleNewsletterDto.java
  src/main/java/run/attraction/api/v1/home/service/dto/article/ReceivedArticlesDto.java
  src/main/java/run/attraction/api/v1/mypage/controller/MypageController.java
  src/main/java/run/attraction/api/v1/mypage/service/MypageService.java
  src/main/java/run/attraction/api/v1/mypage/service/dto/archive/article/RecentArticleNewsletterDto.java
  src/main/java/run/attraction/api/v1/mypage/service/dto/archive/article/RecentArticlesDto.java
  src/main/java/run/attraction/api/v1/mypage/service/user/MypageUserService.java
  src/main/java/run/attraction/api/v1/mypage/service/user/MypageUserServiceImpl.java
  src/main/java/run/attraction/api/v1/user/User.java
Labels: feat

#197 style: newsletterThumbnailUrl에서 prefix 제거
  src/main/java/run/attraction/api/v1/home/service/dto/article/ReceivedArticleNewsletterDto.java
  src/main/java/run/attraction/api/v1/home/service/dto/article/ReceivedArticlesDto.java
  src/main/java/run/attraction/api/v1/mypage/service/dto/archive/article/RecentArticleNewsletterDto.java
  src/main/java/run/attraction/api/v1/mypage/service/dto/archive/article/RecentArticlesDto.java
Labels: style

#198 [ATR-460] feat: article과 previousArticle에서 s3 prefix 제거
  src/main/java/run/attraction/api/v1/archive/dto/ArticleDTO.java
  src/main/java/run/attraction/api/v1/introduction/dto/response/PreviousArticleResponse.java
Labels: remove

#199 [ATR-460] feat: article과 previousArticle에서 s3 prefix 제거
  src/main/java/run/attraction/api/v1/archive/dto/ArticleDTO.java
  src/main/java/run/attraction/api/v1/home/controller/HomeController.java
  src/main/java/run/attraction/api/v1/home/service/HomeService.java
  src/main/java/run/attraction/api/v1/home/service/newsletter/HomeNewsletterServiceImpl.java
  src/main/java/run/attraction/api/v1/introduction/dto/response/PreviousArticleResponse.java
  src/main/java/run/attraction/api/v1/mypage/controller/MypageController.java
  src/main/java/run/attraction/api/v1/mypage/service/calendar/MypageCalendarServiceImpl.java
  src/main/java/run/attraction/api/v1/mypage/service/user/MypageUserServiceImpl.java
  src/main/java/run/attraction/api/v1/rank/controller/RankController.java
  src/main/java/run/attraction/api/v1/rank/service/calculator/ConsistencyRankCalculator.java
  src/main/java/run/attraction/api/v1/rank/service/calculator/ExtensiveRankCalculator.java
Labels: remove, style

#200 [ATR-271] feat: 유저 관심사 수정 및 세션 ID 유저 정보 조회 API 구현
  src/main/java/run/attraction/api/v1/auth/controller/AuthController.java
  src/main/java/run/attraction/api/v1/auth/session/SessionService.java
  src/main/java/run/attraction/api/v1/auth/session/dto/UserDetailBySession.java
  src/main/java/run/attraction/api/v1/auth/session/exception/SessionIdNotFoundException.java
  src/main/java/run/attraction/api/v1/auth/session/exception/SessionIdNotFoundExceptionHandler.java
  src/main/java/run/attraction/api/v1/exception/ErrorCode.java
  src/main/java/run/attraction/api/v1/user/Interest.java
  src/main/java/run/attraction/api/v1/user/repository/UserRepository.java
Labels: feat

#201 feat: 유저 관심사 수정 및 세션 ID 유저 정보 조회 API 구현
  src/main/java/run/attraction/api/v1/auth/controller/AuthController.java
  src/main/java/run/attraction/api/v1/auth/session/SessionService.java
  src/main/java/run/attraction/api/v1/auth/session/dto/UserDetailBySession.java
  src/main/java/run/attraction/api/v1/auth/session/exception/SessionIdNotFoundException.java
  src/main/java/run/attraction/api/v1/auth/session/exception/SessionIdNotFoundExceptionHandler.java
  src/main/java/run/attraction/api/v1/exception/ErrorCode.java
  src/main/java/run/attraction/api/v1/user/Interest.java
  src/main/java/run/attraction/api/v1/user/repository/UserRepository.java
Labels: feat

#202 chore: .gitignore 된 파일 삭제
  src/main/resources/log4j2.xml
Labels: chore

#203 [ATR-475] refactor: prometheus uri 하드 코딩 제거
  src/main/java/run/attraction/api/v1/auth/filter/RequestLogFilter.java
Labels: refactor

#205 [ATR-448] feat: 탈퇴 api 수정
  src/main/java/run/attraction/api/v1/mypage/controller/MypageController.java
Labels: feat

#206 [ATR-448] feat: 탈퇴 api 수정 (#205)
  src/main/java/run/attraction/api/v1/mypage/controller/MypageController.java
Labels: feat

#208 [ATR-479] feat: method monitoring (#207)
  src/main/java/run/attraction/api/v1/archive/service/ArchiveService.java
  src/main/java/run/attraction/api/v1/monitoring/MicrometerConfig.java
  src/main/java/run/attraction/api/v1/mypage/service/MypageService.java
  src/main/java/run/attraction/api/v1/rank/controller/RankController.java
  src/main/java/run/attraction/api/v1/rank/service/RankService.java
Labels: feat

#209 [ATR-442] feat: security filter 적용
  src/main/java/run/attraction/api/v1/auth/config/SecurityConfig.java
  src/main/java/run/attraction/api/v1/auth/controller/AuthController.java
  src/main/java/run/attraction/api/v1/auth/filter/ErrorType.java
  src/main/java/run/attraction/api/v1/auth/filter/SessionFilter.java
  src/main/java/run/attraction/api/v1/auth/session/SessionService.java
  src/main/java/run/attraction/api/v1/auth/session/exception/InValidUserException.java
  src/main/java/run/attraction/api/v1/auth/session/exception/ResignedUserException.java
  src/main/java/run/attraction/api/v1/auth/session/exception/SessionExceptionHandler.java
  src/main/java/run/attraction/api/v1/auth/session/exception/SessionIdNotFoundException.java
  src/main/java/run/attraction/api/v1/auth/session/exception/SessionIdNotFoundExceptionHandler.java
  src/main/java/run/attraction/api/v1/auth/session/exception/SessionNotFoundException.java
  src/main/java/run/attraction/api/v1/exception/ErrorCode.java
  src/main/java/run/attraction/api/v1/exception/GlobalExceptionHandler.java
Labels: feat

#210 [ATR-431] feat : 탈퇴 로직 수정 및 filter 적용
  .github/workflows/deploy.yml
  src/main/java/run/attraction/api/v1/auth/config/SecurityConfig.java
  src/main/java/run/attraction/api/v1/auth/controller/AuthController.java
  src/main/java/run/attraction/api/v1/auth/filter/ErrorType.java
  src/main/java/run/attraction/api/v1/auth/filter/SessionFilter.java
  src/main/java/run/attraction/api/v1/auth/session/SessionService.java
  src/main/java/run/attraction/api/v1/auth/session/exception/InValidUserException.java
  src/main/java/run/attraction/api/v1/auth/session/exception/ResignedUserException.java
  src/main/java/run/attraction/api/v1/auth/session/exception/SessionExceptionHandler.java
  src/main/java/run/attraction/api/v1/auth/session/exception/SessionIdNotFoundException.java
  src/main/java/run/attraction/api/v1/auth/session/exception/SessionIdNotFoundExceptionHandler.java
  src/main/java/run/attraction/api/v1/auth/session/exception/SessionNotFoundException.java
  src/main/java/run/attraction/api/v1/exception/ErrorCode.java
  src/main/java/run/attraction/api/v1/exception/GlobalExceptionHandler.java
  src/main/java/run/attraction/api/v1/mypage/service/user/MypageUserServiceImpl.java
Labels: feat

#211 [ATR-431] feat : 탈퇴 로직 수정 및 filter 적용 (#210)
  .github/workflows/deploy.yml
  src/main/java/run/attraction/api/v1/auth/config/SecurityConfig.java
  src/main/java/run/attraction/api/v1/auth/controller/AuthController.java
  src/main/java/run/attraction/api/v1/auth/filter/ErrorType.java
  src/main/java/run/attraction/api/v1/auth/filter/SessionFilter.java
  src/main/java/run/attraction/api/v1/auth/session/SessionService.java
  src/main/java/run/attraction/api/v1/auth/session/exception/InValidUserException.java
  src/main/java/run/attraction/api/v1/auth/session/exception/ResignedUserException.java
  src/main/java/run/attraction/api/v1/auth/session/exception/SessionExceptionHandler.java
  src/main/java/run/attraction/api/v1/auth/session/exception/SessionIdNotFoundException.java
  src/main/java/run/attraction/api/v1/auth/session/exception/SessionIdNotFoundExceptionHandler.java
  src/main/java/run/attraction/api/v1/auth/session/exception/SessionNotFoundException.java
  src/main/java/run/attraction/api/v1/exception/ErrorCode.java
  src/main/java/run/attraction/api/v1/exception/GlobalExceptionHandler.java
  src/main/java/run/attraction/api/v1/mypage/service/user/MypageUserServiceImpl.java
Labels: feat

#212 [ATR-483] refactor: subscribe 폴더 이동
  src/main/java/run/attraction/api/v1/archive/service/ArchiveService.java
  src/main/java/run/attraction/api/v1/home/service/article/HomeArticleServiceImpl.java
  src/main/java/run/attraction/api/v1/home/service/newsletter/HomeNewsletterServiceImpl.java
  src/main/java/run/attraction/api/v1/introduction/Subscribe.java
  src/main/java/run/attraction/api/v1/introduction/repository/SubscribeRepository.java
  src/main/java/run/attraction/api/v1/mypage/service/archive/newsletter/MypageNewsletterServiceImpl.java
  src/test/java/run/attraction/api/v1/mypage/service/archive/MypageNewsletterSerivceTest.java
Labels: refactor

#213 [ATR-485] feat: 해당 뉴스레터 구독 여부 확인 메서드 추가
  src/main/java/run/attraction/api/v1/introduction/controller/SubscriptionController.java
  src/main/java/run/attraction/api/v1/introduction/repository/SubscribeRepository.java
  src/main/java/run/attraction/api/v1/introduction/service/SubscriptionService.java
Labels: feat

#214 [ATR-485] feat: 해당 뉴스레터 구독여부 확인 기능 추가 (#213)
  src/main/java/run/attraction/api/v1/archive/service/ArchiveService.java
  src/main/java/run/attraction/api/v1/home/service/article/HomeArticleServiceImpl.java
  src/main/java/run/attraction/api/v1/home/service/newsletter/HomeNewsletterServiceImpl.java
  src/main/java/run/attraction/api/v1/introduction/Subscribe.java
  src/main/java/run/attraction/api/v1/introduction/controller/SubscriptionController.java
  src/main/java/run/attraction/api/v1/introduction/repository/SubscribeRepository.java
  src/main/java/run/attraction/api/v1/introduction/service/SubscriptionService.java
  src/main/java/run/attraction/api/v1/mypage/service/archive/newsletter/MypageNewsletterServiceImpl.java
  src/test/java/run/attraction/api/v1/mypage/service/archive/MypageNewsletterSerivceTest.java
Labels: refactor, feat

#215 chore: 슬랙 알림 추가
  .github/workflows/deploy.yml
Labels: chore

#218 chore: SecurityConfig monitoring url 적용
  src/main/java/run/attraction/api/v1/auth/config/SecurityConfig.java
Labels: chore

#221 [ATR-487] feat: 뉴스레터 엔티티에 동의 필드 추가 (#220)
  src/main/java/run/attraction/api/v1/introduction/Newsletter.java
  src/main/java/run/attraction/api/v1/introduction/dto/response/NewsletterResponse.java
Labels: feat

#222 [ATR-502] fix: 아티클 보관함 및 최근 받은 아티클 에러 수정
  src/main/java/run/attraction/api/v1/archive/service/ArchiveService.java
  src/main/java/run/attraction/api/v1/home/service/article/HomeArticleServiceImpl.java
  src/main/java/run/attraction/api/v1/introduction/utils/SubscriptionUtil.java
Labels: bug

#223 [ATR-502] fix: 아티클 보관함 및 최근 받은 아티클 에러 수정 (#222)
  src/main/java/run/attraction/api/v1/archive/service/ArchiveService.java
  src/main/java/run/attraction/api/v1/home/service/article/HomeArticleServiceImpl.java
  src/main/java/run/attraction/api/v1/introduction/utils/SubscriptionUtil.java
Labels: bug

#224 [ATR-503] refactor: 뉴스레터 구독 api 리팩터링
  src/main/java/run/attraction/api/v1/archive/controller/ArchiveController.java
  src/main/java/run/attraction/api/v1/archive/service/ArchiveService.java
  src/main/java/run/attraction/api/v1/introduction/controller/SubscriptionController.java
  src/main/java/run/attraction/api/v1/introduction/service/SubscriptionService.java
Labels: refactor

#225 [ATR-503] refactor: 뉴스레터 구독 api 리팩터링 (#224)
  src/main/java/run/attraction/api/v1/archive/controller/ArchiveController.java
  src/main/java/run/attraction/api/v1/archive/service/ArchiveService.java
  src/main/java/run/attraction/api/v1/introduction/controller/SubscriptionController.java
  src/main/java/run/attraction/api/v1/introduction/service/SubscriptionService.java
Labels: refactor

#226 chore: github action git 배포 일시적 비활성화
  .github/workflows/deploy.yml
Labels: chore

#227 chore: github action git 배포 일시적 비활성화 (#226)
  .github/workflows/deploy.yml
Labels: hotfix

#228 [ATR-503] feat: 자동 구독이 가능할 때만 카프카메시지 전송해서 동작하도록 수정
  src/main/java/run/attraction/api/v1/introduction/service/SubscriptionService.java
Labels: feat

#229 [ATR-503] feat: 자동 구독이 가능할 때만 카프카메시지 전송해서 동작하도록 수정 (#228)
  src/main/java/run/attraction/api/v1/introduction/service/SubscriptionService.java
Labels: feat

#230 [ATR-509] fix: 검색 결과 아티클 api 리턴 데이터 수정
  src/main/java/run/attraction/api/v1/archive/repository/ArticleRepository.java
  src/main/java/run/attraction/api/v1/home/service/dto/search/ArticleSearchDto.java
Labels: bug

#231 [ATR-509] fix: 검색 결과 아티클 api 리턴 데이터 수정 (#230)
  src/main/java/run/attraction/api/v1/archive/repository/ArticleRepository.java
  src/main/java/run/attraction/api/v1/home/service/dto/search/ArticleSearchDto.java
Labels: bug

#232 [ATR-510] fix: 구독하지 않은 뉴스레터의 아티클이 보이는 현상 수정
  src/main/java/run/attraction/api/v1/archive/repository/ArticleRepositoryCustom.java
  src/main/java/run/attraction/api/v1/archive/repository/ArticleRepositoryImpl.java
  src/main/java/run/attraction/api/v1/mypage/controller/MypageController.java
  src/main/java/run/attraction/api/v1/mypage/service/MypageService.java
  src/main/java/run/attraction/api/v1/mypage/service/archive/article/MypageArticleService.java
  src/main/java/run/attraction/api/v1/mypage/service/archive/article/MypageArticleServiceImpl.java
Labels: bug

#233 [ATR-510] fix: 구독하지 않은 뉴스레터의 아티클이 보이는 현상 수정 (#232)
  src/main/java/run/attraction/api/v1/archive/repository/ArticleRepositoryCustom.java
  src/main/java/run/attraction/api/v1/archive/repository/ArticleRepositoryImpl.java
  src/main/java/run/attraction/api/v1/mypage/controller/MypageController.java
  src/main/java/run/attraction/api/v1/mypage/service/MypageService.java
  src/main/java/run/attraction/api/v1/mypage/service/archive/article/MypageArticleService.java
  src/main/java/run/attraction/api/v1/mypage/service/archive/article/MypageArticleServiceImpl.java
Labels: bug
