Repository Atractorrr/Attraction-Server, pull requests merged in 2024-09, with the labels that each got.

#293 [ATR-609] feat: SessionFilter 비활성화 기능 추가 (#292)
  src/main/java/run/attraction/api/v1/auth/config/SecurityConfig.java
  src/main/java/run/attraction/api/v1/auth/config/condition/SessionFilterCondition.java
  src/main/java/run/attraction/api/v1/auth/filter/SessionFilter.java
Labels: feat

#295 [ATR-611] chore: 스테이징 서버 ci/cd 설정
  .github/workflows/dev.yml
Labels: chore

#296 [ATR-612] style: 오타 수정
  .github/workflows/dev.yml
Labels: style

#297 [ATR-613] chore: 스테이징 서버에서 사용하지 않는 filebeat 실행 명령어 삭제
  .github/workflows/dev.yml
Labels: chore
